### ISSUE TITLE
export geobuf

### ISSUE THREAD

**Issue by gertcuykens** [osmcode/osmium-tool#102]
Hi, can the following export format be implemented please https://github.com/mapbox/geobuf I believe this wil be faster then using sequential geojson in combination with https://github.com/mapbox/tippecanoe 

Thank you

**Comment by joto** [comment]
I am reluctant to add Geobuf support when there is neither a Geobuf C++ library nor a specifiction to work from.

**Comment by gertcuykens** [comment]
Does this help? It's the part where Tippcanoe reads in geobuf using protozero lib

https://github.com/mapbox/tippecanoe/blob/6b29966e4ae339881c795d5cd9a9d45d9c34fe6e/geobuf.cpp#L535

Basically it just a protobuf 

https://github.com/mapbox/geobuf/blob/master/geobuf.proto

Granted I didn't find any rfc yet for it

**Comment by Komzpa** [comment]
@gertcuykens you can now export your data into PostGIS database and use ST_AsGeobuf.
