### ISSUE TITLE
area matching

### ISSUE THREAD

**Issue by emilburzo** [osmcode/osmium-tool#103]
Love the new area matching for tags-filter!

One thing I didn't fully understand from the code: does the **w**ays filter still also include (possible) **a**reas?

For example if I had a tags-filter of: `nrw/natural=beach`, would the results be identical to `nrwa/natural=beach` ?

Thank you!

**Comment by joto** [comment]
Yes, your examples are identical. `tags-filter` always "or's" matches together. The `a/` filter is a subset of `wr/`, `w/` matches all ways regardless of whether they are closed or not or how many nodes they have.

**Comment by emilburzo** [comment]
Perfect, thank you!
