### ISSUE TITLE
extract command not being displayed after build

### ISSUE THREAD

**Issue by bradleygramhansen** [osmcode/osmium-tool#120]
I have tried building osmium in both Mac OS El-Captain and Ubuntu 16.04 LTS and I get two different problems. When I build in Ubuntu 16.04 `osmium-tool`works, however, `extract` and a few other commands are missing:  
![screen shot 2018-07-10 at 16 38 59](https://user-images.githubusercontent.com/29200730/42521160-0418c95a-8460-11e8-8ce5-7394a744de2b.png)
whereas in Mac OS, I get (this is only a snapshot of the output of calling `pip install osmium`, I have added a full log of the output at the bottom of this message:
<img width="959" alt="screen shot 2018-07-10 at 16 55 25" src="https://user-images.githubusercontent.com/29200730/42522228-8189aba0-8462-11e8-959c-c0427ade3a23.png">
<img width="955" alt="screen shot 2018-07-10 at 16 56 35" src="https://user-images.githubusercontent.com/29200730/42522262-96ce78d8-8462-11e8-810b-81f349a446b0.png">

![screen shot 2018-07-10 at 16 49 22](https://user-images.githubusercontent.com/29200730/42521627-3d78519c-8461-11e8-994a-6f40f5fbc45b.png)
On Mac OS `libosmium 2.14.0` has definitely been installed via homebrew and I have installed `python 3 boost` within the `conda` environment that I am using. 

If you can let me know what `logs` I should send you then I shall gather them. I am hoping to use this tool for processing maps to use with [robosat](https://github.com/mapbox/robosat), which requires the `extract` tool.

A log of the output: [log.txt](https://github.com/osmcode/osmium-tool/files/2181157/log.txt)

Thanks,

Bradley

**Comment by joto** [comment]
If you have missing commands in osmium-tool, you probably have a version that's too old and doesn't have those commands yet. Call `osmium version` to see what version you have. Maybe you are not calling the version you build, but one installed with Ubuntu?

Calling `pip install osmium` doesn't install osmium-tool, but PyOsmium. Please ask there for help.

**Comment by bradleygramhansen** [comment]
Hi @joto, 

Thanks for the prompt reply. The  osmium version is 1.3.0 - that makes sense now! Although, I am not sure why homebrew installed that version. 

I shall post on there now.
