### ISSUE TITLE
Feature-Request - Renumber: Specify an Offset

### ISSUE THREAD

**Issue by amenk** [osmcode/osmium-tool#122]
Can we add an base offset for the renumber command?
Use case would be to renumber in a way that does not conflict with the OSM ID universe, so we would choose sum ridiculously high offset for the renumber command.
We currently were using negative IDs, but those cause problems all over the place (in other tools) :-)

**Comment by joto** [comment]
This was requested a few times, so I have written this now. It is available in master. See the `--start-id` option. Please test.

**Comment by amenk** [comment]
Built the master, tried it. Works well - thanks a lot!
