### ISSUE TITLE
Renumber: Only renumber negatives, pick next free IDs

### ISSUE THREAD

**Issue by amenk** [osmcode/osmium-tool#123]
Can we include a feature that renumbers only negative IDs in a way to pick the next free ID from a start-number (in combination with the start-id) ?

Use case: Do not use negative IDs, use IDs that do not conflict with the OSM universum, edit file using JOSM but keep already assigned IDs stable.

**Comment by joto** [comment]
This is a rather specialized use case. I'll leave it open here but it is unlikely I'll work on it.

**Comment by amenk** [comment]
True.

I think it's better to get negative ids working across tools. Figured it out in my case.

If anybody needs it they can reopen that one.
