### ISSUE TITLE
All relations are missing after tags-filter non highway

### ISSUE THREAD

**Issue by weizhiyong** [osmcode/osmium-tool#132]
The commands to execute:
1. wget -nv --output-document=planet.osm.pbf https://planet.osm.org/pbf/planet-180827.osm.pbf
2. osmium tags-filter -o filtered-planet.osm.pbf planet.osm.pbf w/highway w/route=ferry

After non-highway is filtered, all relations are missing too per information by osmium fileinfo:
1. Number of relations are 0 for filtered-planet.osm.pbf 
2. Number of relations are 6025710 for planet.osm.pbf 

-----------------------------------------------------------------------------------------------------------
$ osmium fileinfo -e filtered-planet.osm.pbf 
File:
  Name: filtered-planet.osm.pbf
  Format: PBF
  Compression: none
  Size: 13717592879
Header:
  Bounding boxes:
    (-180,-90,180,90)
  With history: no
  Options:
    generator=osmium/1.8.0
    osmosis_replication_timestamp=2018-08-27T02:00:01Z
    pbf_dense_nodes=true
    timestamp=2018-08-27T02:00:01Z
[======================================================================] 100% 
Data:
  Bounding box: (-180,-90,180,87.0002)
  Timestamps:
    First: 2005-05-01T14:56:35Z
    Last: 2018-08-27T02:00:01Z
  Objects ordered (by type and id): yes
  Multiple versions of same object: no
  CRC32: 708e4bf4
  Number of changesets: 0
  Number of nodes: 1179101262
  Number of ways: 124217098
  Number of relations: 0
  Largest changeset ID: 0
  Largest node ID: 5859950852
  Largest way ID: 620204251
  Largest relation ID: 0

-----------------------------------------------------------------------------------------------------------
$ osmium fileinfo -e planet.osm.pbf 
File:
  Name: planet.osm.pbf
  Format: PBF
  Compression: none
  Size: 44444988771
Header:
  Bounding boxes:
    (-180,-90,180,90)
  With history: no
  Options:
    generator=planet-dump-ng 1.1.6
    osmosis_replication_timestamp=2018-08-27T02:00:01Z
    pbf_dense_nodes=true
    pbf_optional_feature_0=Has_Metadata
    pbf_optional_feature_1=Sort.Type_then_ID
    timestamp=2018-08-27T02:00:01Z
[======================================================================] 100% 
Data:
  Bounding box: (-180,-90,180,90)
  Timestamps:
    First: 2005-05-01T14:56:35Z
    Last: 2018-08-27T02:00:01Z
  Objects ordered (by type and id): yes
  Multiple versions of same object: no
  CRC32: 466cb1fe
  Number of changesets: 0
  Number of nodes: 4695188826
  Number of ways: 519982451
  Number of relations: 6025710
  Largest changeset ID: 0
  Largest node ID: 5859950885
  Largest way ID: 620204251
  Largest relation ID: 8601809

**Comment by joto** [comment]
That is the expected behaviour. `w/highway w/route=ferry` means you want all ways tagged with `highway=...` or `route=ferry`. So you are not getting any relations.

**Comment by joto** [comment]
You already know how to get all ways tagged `highway`. You can use `osmium cat -t relation` to get all relations. Then use `osmium cat` again to concatenate the two files you got. If you only want those relations which actually mention the `highway` ways, you can use the `osmium getparents` command available in the newest version of `osmium` (1.9.1). You should be able to figure out the details from the man pages.
