### ISSUE TITLE
osmium extract should create out directory

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/osmium-tool#133]
When users specify an outdir in the config such as `/tmp/osm` and run

    osmium extract -c config.json basemap.osm.pbf

we error out with

> Open failed for '/tmp/osm/map.osm.pbf': No such file or directory

if `/tmp/osm` is not an existing directory.

osmium extract should create the outdir or at least change the error message to point out the out directory does not exist, and not that the open call to a specific pbf file did not succeed.

**Comment by joto** [comment]
I have added a better error message. This kind of stuff is always annoying, because it needs extra code for Windows which I can't test properly. Lets hope it works. :-)
