### ISSUE TITLE
osmium extract's memory requirements with multiple bounding boxes

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/osmium-tool#134]
Suppose I want to extract the road network of all major cities in North America for some routing analysis.

I can filter the pbf to only contain roads and its nodes with

```
osmium tags-filter north-america-latest.osm.pbf \
  -o north-america-2018-09-12-roads.osm.pbf \
  'w/highway'
```

Now when I want to cut it into hundreds of bounding boxes via

```
osmium extract \
  -s simple \
  -c config.json \
  north-america-2018-09-12-roads.osm.pbf 
```

where my config has hundreds of bbox entries osmium extract requires hundreds of GBs to run this out.

I suppose the amount of required memory depends on the input pbf size but also on the number of bboxes I want to extract. Can this be made more efficient? Should users be able to e.g. batch extract n bboxes at once? Or are users supposed to batch multiple configs manually?

The workaround is to split the single config with hundreds of bounding boxes into multiple configs and run osmium extract multiple times (for each config) manually.

**Comment by joto** [comment]
This problem has come up a few times. The recommended solution is to split up your config and do this recursively, going to smaller and smaller bboxes.

I haven't found a way to make this magically more efficient. Osmium would have to guess somehow how to split your job in the best possible way (or, at least, a reasonable way). But this depends on the input data, the bboxes (or other output) you want, the amount of memory you have, how fast your disks are etc. I'd rather keep the program simple and let the user (who knows more about their problem and the environment) decide this outside Osmium. But I am open to suggestions.

**Comment by joto** [comment]
I have put a not into the README. This has to be enough for the moment.

**Comment by daniel-j-h** [comment]
:+1:
