### ISSUE TITLE
Is it possible to keep a planet history file up-to-date?

### ISSUE THREAD

**Issue by d3netxer** [osmcode/osmium-tool#138]
Is it possible to keep a planet history file up-to-date? Maybe by downloading diff files on a regular basis and applying them (using the osmium diff command?) ? Or is there a better way to do this?

**Comment by joto** [comment]
Not with the Osmium tool, but [PyOsmium](https://osmcode.org/pyosmium) has a program for this: https://github.com/osmcode/pyosmium/blob/master/tools/pyosmium-up-to-date
