### ISSUE TITLE
bounds tag missing in extracted data

### ISSUE THREAD

**Issue by sphoto** [osmcode/osmium-tool#139]
I am trying to extract the Balearic Islands from Spain:
<code>osmium extract -p balearic.poly spain-latest.osm.pbf -o balearic.osm</code>
The extracted data differs from the one made by osmosis:
1. bounds tag is missing
2. contains data from Africa and the spanish mainland (e.g. ferry terminal nodes) 

It is possible to get the same extract as from osmosis?

**Comment by joto** [comment]
1. As the man page says: "By default no bounds will be set in the header of the output file.  Use the --set-bounds option if you need this."
2. I don't know what exact strategy Osmosis is using. You can read about strategies that Osmium supports in the Osmium man page.

**Comment by sphoto** [comment]
Got it , thank you.
