### ISSUE TITLE
"AND" logic for tags-filter

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/osmium-tool#143]
AFAIK for now you can only use `OR` logic in tags-filter tool. So any of matching expressions provide an output result. It'd be great to have an `AND` logic, so only all matching expressions provide a result.
Possible?

**Comment by joto** [comment]
Run it twice, first with one tag list, then with the other. Works in some cases at least. For easier use I have avoided allowing complex logical expressions, although I do see that it might be nice to have them sometimes. 

The idea is here that if you want to do more complex processing, you'll need a "real" language anyway. So my recommendation is always to use the fast Osmium to pre-filter the data roughly, then use a different solution (which can be slower) on the now much reduced dataset. This could be PyOsmium or you can use the OPL format and do this in any scripting language.
