### ISSUE TITLE
Support Augmented Diffs file format

### ISSUE THREAD

**Issue by nlehuby** [osmcode/osmium-tool#147]
Would you consider to add Augmented Diffs as a change files format in addition to `.osc` ?

https://wiki.openstreetmap.org/wiki/Overpass_API/Augmented_Diffs#Contained_data

This would be very useful to make data analysis from OSM history files.

**Comment by joto** [comment]
Augmented diffs don't need a different file format, they need different data. That's not something that can be solved on the libosmium-level. You need some kind of program that keeps a database of OSM data, reads changes files and "augments" the change files with the data from the database. But the results are still change files (or history files, however you want to create them).

**Comment by nlehuby** [comment]
Thanks for your answer.

I'm not sure to understand what is lacking in osmium to do that.

If you extract two history files, filter them by tags and make a diff between the two, you get something that is very close to the augmented diff result.
See for instance this [example use case](https://github.com/Jungle-Bus/OSMTherapist/blob/master/osmium-tool/readme.md) to get detailled diff on some kind of objects between two dates using osmium-tool.

**Comment by joto** [comment]
Do I understand this correctly: You want to do what you are doing in your [example use case](https://github.com/Jungle-Bus/OSMTherapist/blob/master/osmium-tool/readme.md) but instead of doing the `osmium diff` at the end, you want to create basically the same diff output, but in augmented diff format?

**Comment by nlehuby** [comment]
Yes ! Something like `osmium diff input1.osm.pbf input2.osm.pbf -f output.adiff.xml` I guess

**Comment by joto** [comment]
I looked into this a bit and it isn't easy to do.

First, augmented diffs as created by Overpass contain the locations of the nodes in the ways and extra information on relation members. Adding this isn't possible without a whole lot of extra effort creating some kind of database etc. Adding this would definitely be more than the `osmium diff` command could handle.

But even if we didn't do this, there is a second problem: The format used by augmented diffs with the `<action>` sections with embedded `<old>` and `<new>` sections is difficult to create with libosmium. The XML writer only looks at one object at a time and writes it out. But for this format it would have to look at two objects at a time, decide what their relation is and write them out together. This would need huge changes in libosmium and osmium-tool, so this is unlikely to happen any time soon.

**Comment by nlehuby** [comment]
Ok. Thanks a lot for taking the time to investigate this in detail :heart: 
I'll try to find another way to achieve my goal.

**Comment by Komzpa** [comment]
Can Overpass Augmented Diff format be used as input though?

Potentially they can be converted into a set of delete/insert queries for updating the database created using `osmium export` - they're bundling everything you need to reconstruct geometries already, allowing to skip maintaining the database of intermediate geometries altogether.
