### ISSUE TITLE
declare upper bound for libosmium version

### ISSUE THREAD

**Issue by das-g** [osmcode/osmium-tool#149]
As libosmium uses semantic versioning, major versions should be expected to be incompatible. Thus, osmium-tool should IMO declare (both in the build instructions and in CMakeLists) not only a lower bound for the required libosmium version (as it already does), but also an upper bound that ties it to the then-current major version of libosmium.

(If a libosmium major release occurs whose incompatibilities happen to not affect osmium-tool, a minor osmium-tool version can be released that bumps that upper bound.)

I noticed this when researching #148.

**Comment by joto** [comment]
I am not sure how to do that in CMake without a lot of extra work. The `find_package()` command doesn't support that.

And it is doubtful whether adding something like this for the future which might never come or come in some other way than expected, is very helpful.
