### ISSUE TITLE
Support exporting type=restriction relations

### ISSUE THREAD

**Issue by Komzpa** [osmcode/osmium-tool#152]
Hi,

I'd like to use `osmium export` together with pgrouting. To do so, I need to get turn restriction relations into my tables somehow.

The way I see it now: 

 - geometry in form of GEOMETRYCOLLECTION(LINESTRING(from), POINT(via), LINESTRING(to));
 - tags are tags, "type" not thrown away (so type=restriction);
 - way_nodes may be list of nodes of from, via, to in order of traversal.
 - I'm in doubt about needing from, via, to osm_type and osm_id for reconstruction. There is no field for them currently. They may go into tags, or a new json "members" column, or nowhere at first iteration.

A restriction that can't be sewed together into single linestring of from-via-to shall be considered broken and thrown away with optional warning.

Are there any better options to do it?

**Comment by joto** [comment]
`osmium export` is a minimal solution for getting OSM data into different formats. It is not intended as a general database import tool and it will never be. You can use libosmium to build your own database import tool that can do everything it wants. Or you can use `osmosis` which does a 1:1 import of OSM data into a database and you can do your postprocessing in the database then. For your case there is an `osm2pgrouting` tool out there, I suggest you look into that.
