### ISSUE TITLE
[feature]

### ISSUE THREAD

**Issue by kkdd** [osmcode/osmium-tool#155]
Hello,
I would like to check whether objects are ordered by type only, by using ```osmium fileinfo -e```.
I realizes that it checks ```ordered both by type and id``` as of now, as follows:

```console
$ osmium fileinfo -e japan-highway.osm.pbf | grep ordered
  Objects ordered (by type and id): yes
```

ref. [[feature] ensuring reading all nodes before reading any ways in an OSM file #276](https://github.com/osmcode/libosmium/issues/276)

**Comment by joto** [comment]
Most programs need OSM files ordered by type and ID, so it makes sense to check for that. OSM files that are ordered by type but not by ID aren't that common. Unless somebody can convince me that this is something really useful and commonly needed, I don't think I'll add that.
