### ISSUE TITLE
Canceling deletes input file?

### ISSUE THREAD

**Issue by jaksco** [osmcode/osmium-tool#156]
This is my first time using osmium. I ran this command:

```
osmium tags-filter planet-190218.osm.pbf amenity=restaurant amenity=cafe amenity=fast_food \
    -o food.osm
```

and I realized I wanted to output to pbf instead so I did `ctrl-c` in the terminal but when I ran it again with 'food.pbf' as the output it said that `planet-190218.osm.pbf` was not found. I looked for it by running `ncdu` and it's nowhere. So now I need to spend 4 hours downloading planet.osm.pbf again

**Comment by jaksco** [comment]
osmium version 1.9.1
libosmium version 2.14.2

**Comment by joto** [comment]
I have no idea what happened there, but there is no code in Osmium that deletes any file under any circumstances, so I am pretty sure it wasn't Osmium.

**Comment by jaksco** [comment]
That's what I wanted to know. I'll close the issue for now and use bash shell when I'm running osmcode. This was definitely the "weird computer happening" of my year
