### ISSUE TITLE
Add option to set osm id for a polygon in osmium extract config file 

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/osmium-tool#158]
When using osm file as a polygon for `osmium extract` it'd be nice to have an option to choose which object to use as an extract boundary.

Imagine the workflow where you first do an `osmium getid` to get multiple regions from a planet file and then want to extract them in one go using a config file. 

Currently you have to do more `osmium getid` to get regions one by one and then use them as polygons in config file. Could this be done internally by `osmium extract` tool?

**Comment by joto** [comment]
Could be done, but would need some effort. I am more of a friend of "one tool to do one thing and do it right", but I see that this could be useful.

**Comment by joto** [comment]
Use `osmium getid -r -t` (the `-t` is new in the latest version) to get the correct boundaries. This is more flexible. Building this into the `extract` command would make this more complicated for a very specific use case.
