### ISSUE TITLE
osmium dies suddenly...

### ISSUE THREAD

**Issue by merspieler** [osmcode/osmium-tool#160]
I'm trying to split the world-latest.osm.pbf file in one by one degree tiles.

When I've tried it in one go, I've got `Resources temporarely not available`.  
A search showed me that I probably hit the limit of max open files or threads so I've added the following to `/etc/security/limits.conf`:
```
<user>          hard    nofile          655355
<user>          soft    nofile          655355
<user>          hard    nproc           655355
<user>          soft    nproc           655355
```
Which didn't solve the problem. Maybe I've hit some hardware/os limits?

So I've reverted the changes and tryed to reduce the number of tiles I cut in one go.  
Processing 1/4 of the world wasn't enough. So I've ended up, processing a one by 360 degree area at a time which resolves the problem above...

But now I run into another problem... after about 70 minutes it dies... I've tried to run it with gdb but all i see is:
```
Program terminated with signal SIGKILL, Killed.
The program no longer exists.
```

Running version 1.10.0 on debian buster 
System spec:
* 4 Core 64bit Intel CPU
* 16GB RAM
* 1TB HDD

I run osmium as follows:  
`osmium extract -c <config> planet-latest.osm.pbf`

How can I fix that?

**Comment by joto** [comment]
Most likely you don't have enough memory, read the `osmium help extract` man page under `MEMORY USAGE` and read up about Linux memory management. Use your favourite search engine to look for "linux memory management" or "oom-killer".

**Comment by merspieler** [comment]
I'll do, thanks

**Comment by merspieler** [comment]
I'll take the advice of the manpage and do it in more steps...
