### ISSUE TITLE
manpages break long options

### ISSUE THREAD

**Issue by andrewharvey** [osmcode/osmium-tool#161]
It appears, at least in the debian packages, that the manpages generation is breaking `--` long style options. eg. what should be `--no-progress` becomes `-no-progress` in the manpage.

**Comment by joto** [comment]
Thanks for the report. I tracked this down to a change in pandoc. In newer versions the markdown reader interprets `--` as an en-dash which the roff-writer writes as `[en]` which is then displayed as a single `-`. I'll open an issue with pandoc to see whether this is considered a bug by them.

**Comment by joto** [comment]
Okay, I think I have fixed this now in a way that it works with old and new pandoc versions by escaping the dashes (`\--`).
