### ISSUE TITLE
Exact meaning of include_tags in export

### ISSUE THREAD

**Issue by rogorido** [osmcode/osmium-tool#162]
Probably I'm misunderstanding the meaning of include_tags... But shouldn't these two commands yield the same result?

`osmium tags-filter chile-latest.osm.pbf -o chile-iglesias.osm amenity=place_of_worship --fsync --overwrite`
`osmium export chile-iglesias.osm -o chile-iglesias.pg -v`
`

and 
`
osmium export chile-latest.osm.pbf -o chile-iglesias.pg -v -c config-pg.json
`

using the following config file: 

`
{
    "attributes": {
        "type":      false,
        "id":        false,
        "version":   false,
        "changeset": false,
        "timestamp": false,
        "uid":       false,
        "user":      false,
        "way_nodes": false
    },
    "linear_tags":  true,
    "area_tags":    true,
    "exclude_tags": [],
    "include_tags": ["amenity=place_of_worship"]
}
`

**Comment by joto** [comment]
No, these are different things. `osmium tags-filter` filters *objects* while the `include_tags` filters *tags*. So if you are only interested in any objects with certain tags, you use `tags-filter`. But if you want to see all objects but only certain tags of those objects, you use the  `include_tags` feature of `osmium export`. Also keep in mind that `osmium tags-filter` will also give you referenced objects (nodes in ways, members in relations) even if they don't contain the tag.

**Comment by rogorido** [comment]
Ok. I was pretty sure, that I was misunderstanding something... Thanks for your answer and above all thanks for the wonderful program and libraries!
