### ISSUE TITLE
osmium tags-filter fails on minutely changesets from planet.osm.org

### ISSUE THREAD

**Issue by Timost** [osmcode/osmium-tool#163]
Hi,
First of all, thank you for all the work that has been put in this project, I've tried a lot of tooling around openstreetmap and in my experience osmium is by far the best I could find.

I'm currently using a combination of `pyosmium-get-changes` and `osmium tags-filter` to fetch the minutely changesets from planet.osm.org and import them in elasticsearch. The whole process runs in a docker container (based on debian testing) and is triggered by a kubernetes cronjob.

Recently this combination stopped working, `pyosmium-get-changes` seemingly runs fine but when I use `osmium tags-filter` on its output it fails. See the whole process below:
```
root@b092b87c85a7:/opt/app# pyosmium-get-changes -o test_changesets_bug/rawchangesets.osc -I 3462136 --server https://planet.osm.org/replication/minute/ --size 1 -vvv
INFO: Using replication server at https://planet.osm.org/replication/minute/
DEBUG: Using given sequence ID 3462136
DEBUG: Starting download at ID 3462137 (max 1 MB)
DEBUG: Downloaded change 3462137. (923 kB available in download buffer)
DEBUG: Downloaded change 3462138. (879 kB available in download buffer)
DEBUG: Downloaded change 3462139. (859 kB available in download buffer)
DEBUG: Downloaded change 3462140. (784 kB available in download buffer)
DEBUG: Downloaded change 3462141. (660 kB available in download buffer)
DEBUG: Downloaded change 3462142. (494 kB available in download buffer)
DEBUG: Downloaded change 3462143. (414 kB available in download buffer)
DEBUG: Downloaded change 3462144. (389 kB available in download buffer)
DEBUG: Downloaded change 3462145. (297 kB available in download buffer)
DEBUG: Downloaded change 3462146. (282 kB available in download buffer)
DEBUG: Downloaded change 3462147. (99 kB available in download buffer)
DEBUG: Downloaded change 3462148. (-56 kB available in download buffer)
3462148
root@b092b87c85a7:/opt/app# osmium tags-filter test_changesets_bug/rawchangesets.osc -o test_changesets_bug/changesets.osc -e osmium-tags-filter.txt --overwrite -v
[ 0:00] Reading expressions file...
[ 0:00] Started osmium tags-filter
[ 0:00]   osmium version 1.10.0
[ 0:00]   libosmium version 2.15.0
[ 0:00] Command line options and default settings:
[ 0:00]   input options:
[ 0:00]     file name: test_changesets_bug/rawchangesets.osc
[ 0:00]     file format:
[ 0:00]   output options:
[ 0:00]     file name: test_changesets_bug/changesets.osc
[ 0:00]     file format:
[ 0:00]     generator: osmium/1.10.0
[ 0:00]     overwrite: yes
[ 0:00]     fsync: no
[ 0:00]   other options:
[ 0:00]     add referenced objects: yes
[ 0:00]   looking for tags...
[ 0:00]     on nodes: yes
[ 0:00]     on ways: yes
[ 0:00]     on relations: yes
[ 0:00] Following references...
[ 0:00]   Reading input file to find relations in relations...
[ 0:00]   Reading input file to find nodes in ways...
osmium: /usr/include/osmium/osm/node_ref_list.hpp:152: bool osmium::NodeRefList::is_closed() const: Assertion `!empty()' failed.
Aborted (core dumped)

```
I'm using:
- osmium version 1.10.0
- libosmium version 2.15.0
- pyosmium version 2.15.2 (python 3.6.8)

`osmium-tags-filter.txt ` looks like this:
```
amenity
restaurant
fast_food
cuisine
diet
shop
clothes
bar
sport
leisure
tourism
public_transport
train
railway
bus
tram
office
aerodrome
craft
recreation_ground
```

Interestingly the process runs fine on changesets from geofabrik.de on country changesets, so I'm not quite sure what is going on. Although the logs above are from a docker container, I'm able to reproduce this on my computer as well (debian testing).

**Comment by joto** [comment]
First, *change files* are not the same as *changesets*. A *changeset* is a particular data type, see [the wiki](https://wiki.openstreetmap.org/wiki/Changeset). A *change file*, sometimes called a *diff file* contains changes between two versions of the OSM database, it usually has the suffix `.osc`.

Now you found a bug in Osmium. It is triggered when a way is deleted in a change set. Maybe you have never before had deleted ways in the changesets and that's why you are only seeing it now. I fixed that bug, but `osmium tags-filter` will probably still not work for you. I have added a note to the man page that `tags-filter` isn't supposed to work with change files.

`osmium tags-filter` doesn't work on change files, because change files only contain changed data and not complete data. You can use `osmium tags-filter` with the `-R` option, then it should "sort-of" work, depending on what you are doing with the data. If you want to do this, you really have to understand the OSM data model in detail and know how the change files work. In particular you can't use the recursive feature of `tags-filter` which makes your dataset incomplete and you will not see deletions of the objects in your dataset because `tags-filter` can't know which tags a deleted object used to have.

**Comment by Timost** [comment]
Thank you for your fast answer @joto, and for pointing out my confusion between change files/diffs and changesets. I've gone back to the openstreemap documentation and the osmium manual to try to understand better how diffs work.

What I'm trying to do is essentially what `osmium apply-changes` does but for an elasticsearch database. So I want to translate the diffs into operations to apply to the elasticsearch index to keep it up to date.

I store only a subset of the openstreetmap data and I use `osmium tags-filter` to extract this subset from the `planet` file.

From the [OsmChange](https://wiki.openstreetmap.org/wiki/OsmChange) documentation, I understood that the create and modify operations are made at the "node/way/relation level" and that therefore each change must provide the entirety of the tags data for nodes and the nodes/ways that are part of a way/relation. Only the delete operation can have "partial" data. Is this assumption wrong ?

In the end, I only store single nodes and areas (in the osmium sense). I don't store nodes that are part of a way separately. When a way, is deleted I simply delete the corresponding object in the database since I don't handle the nodes that are part of it separately. 

I would really appreciate, if you had the time to give me a bit more detail on:

> because change files only contain changed data and not complete data.

Do you mean by that that `modify` action on a way only references the nodes' ids and the node themselves are not included in the diff (coordinates, tags etc...) ? If it's the case, I've overlooked this fact. And I would need to store all the nodes (even the ones that are part of a way) somewhere and also keep this database up to date.

**Comment by joto** [comment]
If you really want to do this correctly, you have to do a lot more than you are doing now. If an existing way changes its tags, for instance, there are several cases you have to handle: If it didn't have an "interesting" tag before, but does now, you'll need the nodes, so you have to store *all* nodes to handle this. If it had an "interesting" tag, but doesn't in the new version, you have to delete it from your database. For areas, you have a similar problem with ways as relation members etc.

**Comment by Timost** [comment]
Ok I see your point now. Thank you for taking the time to explain this, there are indeed some issues with what I did so thank you for pointing them out.
