### ISSUE TITLE
Replace JSON with hstore in pg export

### ISSUE THREAD

**Issue by majkrzak** [osmcode/osmium-tool#167]
When exporting data in `pg` format, JSON is used to store tags information. Due to the tags specification hstore is more suitable in this aspect. Another option is to change this behaviour according to some option.

**Comment by joto** [comment]
Yes, would be nice to have this as an option. I have chosen JSON because it is built into PostgreSQL and doesn't need an extension. So it is slightly easier to use and "more standard" for what its worth.

**Comment by majkrzak** [comment]
If you will specify for example how the option should look like I can do it
maybe this evening.

wt., 18 cze 2019, 10:19 użytkownik Jochen Topf <notifications@github.com>
napisał:

**Comment by joto** [comment]
I am not sure myself. I think we need some generic "file format option"-option. Because chances are that we want more options in the future. We already have the `-r`, `--omit-rs` option which is specific to one output format and I don't like that.

**Comment by majkrzak** [comment]
Making queries with JSON is very time consuming comparing to hstore. It
takes at least 10 times more, it didn't finished yet

wt., 18 cze 2019, 10:41 użytkownik Jochen Topf <notifications@github.com>
napisał:

**Comment by joto** [comment]
This is now available in master using the option `-x tags_format=hstore` (or equivalent setting in the config file).
