### ISSUE TITLE
documentation: tags-filter clarification

### ISSUE THREAD

**Issue by chapmanjacobd** [osmcode/osmium-tool#168]
1. Will `--invert-match` work with "normal mode"? Or is it mutually exclusive? Right now the documentation makes it seem like they are separate modes

I expect that the following will remove disused and abandoned railway stations and bus stops. Is my assumption correct?

```
osmium tags-filter planet.pbf  \
  highway=bus_stop \
  railway=station \
-i disused \
   abandoned \
-o transport.pbf --progress --fsync
```

2. Will `*=value` work?
If I do `-i *=disused` will tags-filter remove the objects that have that value under any key? 

Mostly my feedback is this: Thanks so much for making tags-filter! I really like it

edit: the progress bar finally loaded so I guess it's working :D we'll see if the results are as expected

**Comment by chapmanjacobd** [comment]
ah yeah the file was starting to get to 10GB at 19% so I think the modes are mutually exclusive. I'll try running `--invert-match` after creating a selection of transport.pbf from planet.pbf

**Comment by joto** [comment]
`-i` completely inverts the tags filter, there is no mixing of what you call "normal mode" and "-i". And no, `*=value` isn't supported.

**Comment by chapmanjacobd** [comment]
I think using `-i` with `-t` might lead to some unexpected results? I tried one run with `-t` and one run without `-t` and I got files with the same number of nodes, ways, and relations. The only difference between the files is the number of buffers. The files have different md5 values. 

both
  Number of nodes: 1357648283
  Number of ways: 140100571
  Number of relations: 866229

with `-t` 
  Number of buffers: 2072472 (avg 723 objects per buffer)
  Sum of buffer sizes: 131852973552 (131.852 GB)
  Sum of buffer capacities: 136048148480 (136.048 GB, 97% full)

without `-t` 
  Number of buffers: 2096772 (avg 714 objects per buffer)
  Sum of buffer sizes: 133436320264 (133.436 GB)
  Sum of buffer capacities: 137640673280 (137.64 GB, 97% full)

I was under the impression that lossless compression would always result in the same file. I guess I don't really understand what protocol buffers are. You don't need to respond to this unless it is abnormal to you and you need more info from me. I will not use `-t` with `-i`... thanks
