### ISSUE TITLE
osmium-extract doesn't extract all features when given osm polygon boundary

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/osmium-tool#169]
It does work well if the boundary file consists of one relation with only ways and nodes as members. 
But when a boundary file has a relation with nested relations most features don't get extracted. 
Here's an example workflow:
```
# First get a boundary file
osmium getid -r -v -o bry.bnd.pbf planet-latest.osm.pbf r81997
# Same as https://www.openstreetmap.org/api/0.6/relation/81997/full

# Then do an extract with it
osmium extract -v --overwrite -s smart -o bry_test.pbf -p bry.bnd.pbf planet-latest.osm.pbf
```

The output file is quite small with only a few osm features extracted.

**Comment by ImreSamu** [comment]
imho: this is  a `role=subarea` related problem ..   see:  https://github.com/osmcode/osmium-tool/issues/124

**Comment by joto** [comment]
Nested relations are not supported.
