### ISSUE TITLE
Osmium command not found

### ISSUE THREAD

**Issue by VicXue** [osmcode/osmium-tool#171]
I installed this on my Ubuntu machine. I have build and make the osmium-tool successfully and passed all the ctests. However, when I called osmium command in the terminal, it returns this message: 

> Command 'osmium' not found, but can be installed with: 
sudo apt install osmium-tool

I follow the instructions in the README: 
mkdir work
cd work
git clone https://github.com/mapbox/protozero
git clone https://github.com/osmcode/libosmium
git clone https://github.com/osmcode/osmium-tool

I build and make the osmium-tool without building and making the other two packages. I also used ctest to check and all tests are passed. Is there anything I have done wrong?

**Comment by Nakaner** [comment]
Thank you for your interest in Osmium.

The final executable binary file is located in the `build/` directory. Please mind that you need to add the full path and not its file name only to excute a binary which is located in a directory not listed in your `$PATH` environment variable.

This is not a bug of Osmium. See the following resources how to execute programs a Unix command line and what the PATH variable is:

https://www.linuxquestions.org/questions/linux-newbie-8/how-to-run-program-from-command-line-313900/#post1594428

http://www.linfo.org/path_env_var.html

**Comment by cormundo** [comment]
Hello,

I'm running into the same problem - I'm using Google's Cloudshell in this case. Does that cause problems with above mentioned PATH variable? I'm completely new to Linux and command line projects so this is a bit confusing for me

Am I supposed to run both` cmake` .. and `ccmake` , then `make`? It's giving me errors after I first run cmake. 

Thanks, C
