### ISSUE TITLE
Cannot filter change-sets by username

### ISSUE THREAD

**Issue by VicXue** [osmcode/osmium-tool#172]
I'm trying to filter a pbf file by contributors. I first convert the pbf file to a change-set using `osmium cat my.osm.pbf -o my.osm.bz2`. Then, I tried to filter the change-set by using `osmium changeset-filter -u VictorXue my.osm.bz2 -o vic.osm.bz2`. However, this outputs a bz2 file containing an osm file with headers only. I'm not sure if I'm doing something wrong. 
The my.osm.bz2 file looks like this:

```
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmium/1.10.0">
 ...
   <node id="2315111168" version="2" timestamp="2019-07-07T23:11:10Z" uid="10137513" user="VictorXue" changeset="71993431" lat="-37.7901967" lon="175.3661364"/>
   <node id="2315117009" version="3" timestamp="2019-07-15T04:54:08Z" uid="10137513" user="VictorXue" changeset="72247912" lat="-37.8207101" lon="175.3805573"/>
 ...
  <way id="704706432" version="1" timestamp="2019-07-15T22:39:27Z" uid="10137513" user="VictorXue" changeset="72283236">
     <nd ref="6617860909"/>
     <nd ref="6617860910"/>
     <nd ref="6617860911"/>
     <nd ref="6617860912"/>
     <nd ref="6617860913"/>
     <nd ref="6617860909"/>
     <tag k="natural" v="wood"/>
   </way>
...
```
Version:
osmium version 1.10.0 (v1.10.0-42-g7341b94)
libosmium version 2.15.1

**Comment by joto** [comment]
I think you are a bit confused on what a "changeset" is. There is a description [here](https://wiki.openstreetmap.org/wiki/Changeset). What you seem to have are normal OSM files, for those you don't use `osmium changeset-filter`, but `osmium tags-filter`. There is also the concept of "change files" or "diff files", sometimes also called "replication diffs", those are the files that end in `.osc` (or `.osc.bz2` or so). Those are again, a different beast (but you can filter them with `osmium tags-filter` also).

**Comment by VicXue** [comment]
I see. They both seem to have the same suffix, which confuses me. I should read the manual more carefully. I presume you cannot change between osm files and change-sets? Additionally, if I want to filter by username, should I just use `osmium tags-filter nw/user={myusername}` ?

**Comment by joto** [comment]
Yes, they have the same suffix, that is confusing. OSM files and change files contain totally different data, so no exchange between them.

You can not filter by username with `tags-filter`. Username is not a tag. There is no osmium command to do that currently. As a workaround, you can convert to [OPL format](https://osmcode.org/opl-file-format/) using `osmium cat` and then filter in there using the normal `grep` command. But that's not very comfortable.

File format (osm.bz2, pbf, etc) doesn't matter, they are all handled the same.

**Comment by VicXue** [comment]
@joto I have followed your suggestion and it works just fine. Thank you so much.
