### ISSUE TITLE
OOM for osmium sort with low OSM IDs

### ISSUE THREAD

**Issue by nilsnolde** [osmcode/osmium-tool#179]
Hi,

I tried sorting a "synthetic" OSM file (actually TomTom data) with 300 MB size using `--strategy multipass` and it peaks at ~4.5 GB memory (28% of total RAM) before crashing with OOM. I did read in other issues that multipass isn't as effective since nodes are the main driver.

I followed up with a `osmium fileinfo -e`:
```
Bounding box: (9.5319517,46.3903531,16.1665909,48.7671522)
  Timestamps:
    First: 2019-08-21T17:40:04Z
    Last: 2019-08-21T17:40:04Z
  Objects ordered (by type and id): no
  Multiple versions of same object: unknown (because objects in file are unordered)
  CRC32: not calculated (use --crc/-c to enable)
  Number of changesets: 0
  Number of nodes: 10828663
  Number of ways: 1317373
  Number of relations: 29583
  Smallest changeset ID: 0
  Smallest node ID: 20001001
  Smallest way ID: 5001001
  Smallest relation ID: 1001001
  Largest changeset ID: 0
  Largest node ID: 32263172
  Largest way ID: 6318373
  Largest relation ID: 1030583
  All objects have following metadata attributes: version+timestamp+changeset
  Some objects have following metadata attributes: version+timestamp+changeset
  Number of buffers: 2397403 (avg 5 objects per buffer)
  Sum of buffer sizes: 985742584 (0.985 GB)
  Sum of buffer capacities: 157116203008 (157.116 GB, 1% full)
```
As noted in other issues: it would need 160 GB of RAM with those PBF specs? 50 x the PBF size. I think the ID range is rather smallish for OSM, which I guess is the main memory consumer. 

For reference,  a `osmosis --read-pbf xxx --sort` performs ok. At least no memory issues. Interestingly the output PBF is 100 MB.

**Comment by joto** [comment]
The fileinfo report gives the hint on what's going wrong here:

```
Sum of buffer capacities: 157116203008 (157.116 GB, 1% full)
```

The `1%` is way too small. This should never happen with a normal OSM file. My guess is that your data mixes up nodes, ways, and relations which normally doesn't happen with OSM data (and is probably the reason you want to sort it in the first place). The PBF encoding doesn't work well with mixed object types, it works best when there are long runs of the same object type together and Osmium is optimized for that type of data.

If I am correct with this analysis, you should be able to work around this problem by splitting up your input data into three files, sorting them separately and concatenating them:

```
osmium cat in.osm.pbf -t node -o nodes.osm.pbf
osmium cat in.osm.pbf -t way -o ways.osm.pbf
osmium cat in.osm.pbf -t relation -o relations.osm.pbf
osmium sort -v nodes.osm.pbf -o nodes-sorted.osm.pbf
osmium sort -v ways.osm.pbf -o ways-sorted.osm.pbf
osmium sort -v relations.osm.pbf -o relations-sorted.osm.pbf
osmium cat nodes-sorted.osm.pbf ways-sorted.osm.pbf relations-sorted.osm.pbf -o out.osm.pbf
```

The sort commands should now report much better buffer fullness percentage.

If this works for you I have to think about how to fix the `sort` command, so it can do this without the workaround.

**Comment by nilsnolde** [comment]
Oh, right, didn't know how to interpret the fullness. 

> My guess is that your data mixes up nodes, ways, and relations

Correct indeed. The necessary evil to prevent the parsing of the TomTom data blowing up in memory. The object types are mixed, however, each object type is in ascending order of OSM ID. 

Your workaround works beautifully at a fraction of the memory peak (also of osmosis):

```
[ 0:01] Number of buffers: 9476
[ 0:01] Sum of buffer sizes: 606408992 (0.606 GB)
[ 0:01] Sum of buffer capacities: 621019136 (0.621 GB, 98% full)
[ 0:01] Opening output file...
[ 0:01] Sorting data...
[ 0:03] Writing out sorted data...
[ 0:04] Closing output file...
[ 0:04] Peak memory used: 979 MBytes
```

Of course it'd be great to be able to use `osmium` in this case instead of osmosis. It's rather edge-case though, so I understand if it's not high up in priority. I'll let you close the issue in case you want to leave it open as a reminder.

Thanks for the quick answer!

**Comment by joto** [comment]
The fix might be easier than I thought. I have checked something into the `save-memory-in-sort` branch. Maybe you can test it with your data and see whether that works for you.

**Comment by nilsnolde** [comment]
Very nice, thanks for the quick action! 

You made it work, at least with `--strategy multipass` (`simple` got killed after freezing the OS;)):

```
[ 0:00] Started osmium sort
[ 0:00]   osmium version 1.11.1 (v1.11.1-1-g65a8246)
[ 0:00]   libosmium version 2.15.3
[ 0:00] Command line options and default settings:
[ 0:00]   input options:
[ 0:00]     file names: 
[ 0:00]       /home/nilsnolde/dev/gis-ops/swisstopo/proprietary2osm/data/output/austria_hgv_test_0.pbf
[ 0:00]     file format: 
[ 0:00]   output options:
[ 0:00]     file name: /home/nilsnolde/dev/gis-ops/swisstopo/proprietary2osm/data/output/austria_hgv_test_0_sorted.pbf
[ 0:00]     file format: pbf
[ 0:00]     generator: osmium/1.11.1
[ 0:00]     overwrite: no
[ 0:00]     fsync: no
[ 0:00]   other options:
[ 0:00]     strategy: multipass
[ 0:00] Reading input file headers...
[ 0:00] Opening output file...
[ 0:00] Pass 1...
[ 0:00] Reading contents of input files...
[ 2:46] Number of buffers: 1198671                                            
[ 2:46] Sum of buffer sizes: 606408992 (0.606 GB)
[ 2:46] Sum of buffer capacities: 78556102656 (78.556 GB, 1% full)
[ 2:46] Sorting data...
[ 2:49] Writing out sorted data...
[ 2:51] Pass 2...
[ 2:51] Reading contents of input files...
[ 5:42] Number of buffers: 1198671                                            
[ 5:42] Sum of buffer sizes: 373705624 (0.373 GB)
[ 5:42] Sum of buffer capacities: 78556102656 (78.556 GB, 0% full)
[ 5:42] Sorting data...
[ 5:43] Writing out sorted data...
[ 5:46] Pass 3...
[ 5:46] Reading contents of input files...
[ 8:47] Number of buffers: 89                                                 
[ 8:47] Sum of buffer sizes: 5679936 (0.005 GB)
[ 8:47] Sum of buffer capacities: 5832704 (0.005 GB, 97% full)
[ 8:47] Sorting data...
[ 8:47] Writing out sorted data...
[======================================================================] 100% 
[ 8:47] Closing output file...
[ 8:47] Peak memory used: 75636 MBytes
[ 8:47] Done.
```

It's still a little heavy on RAM (actually aiming for parallel sorting jobs), but definitely does the job.

**Comment by nilsnolde** [comment]
The solution in this specific case is to pull out one PBF for each object type with `osmium cat -t` and merge them again with `osmium cat` to avoid sorting unsorted object type PBFs. This is possible because each of our object type by itself is ordered with ascending OSM IDs. 

Alternatively, write PBF files for each object type in the first place and merge them after. Should be the best performing solution.

Big thanks to @joto for these suggestions during private conversation. You rock.
