### ISSUE TITLE
Note for Windows building

### ISSUE THREAD

**Issue by ibicdlcod** [osmcode/osmium-tool#180]
build-appveyor.bat appears to strictly require VS2015 in default location, but since this is 2019 one can't directly find VS2015Community on https://visualstudio.microsoft.com/ so mentioning this in documentation might help:

https://stackoverflow.com/questions/44290672/how-to-download-visual-studio-community-edition-2015-not-2017

(note you also have to find a separate language pack if not using English)

**Comment by joto** [comment]
Maybe somebody who knows Windows can supply a PR with current and readable instructions for Windows that work on the different versions etc.  I don't understand any of this and will only make it worse if I try to write instructions based on this.
