### ISSUE TITLE
Get exe file of osmium tool

### ISSUE THREAD

**Issue by NiceStepUp** [osmcode/osmium-tool#182]
Good day!
I would like to get exe files of this great tool osmium-tool.

I've found [this link to get latest exe files](https://ci.appveyor.com/project/Mapbox/osmium-tool/build/1.0.390/job/skx61j610842y80u/artifacts), however it says:

> https://ci.appveyor.com/project/Mapbox/osmium-ool/build/1.0.390/job/skx61j610842y80u/artifacts

How is it possible to get exe of osmium-tool?

I am sorry however I do not know C++ and all these tools such as nmake, appVeyor. I've even heard about this tools the first time.

Please, could you help me to get exe files.
I've tried to build using Visual Studio 2017 and written the following command in cmd:

> ...\osmium-tool-master\ build-appveyor.bat

 However, it says:

> System cannot find the path specified.
> ERRORLEVEL:1

Please, be very kind to make latest exe files are available

**Comment by joto** [comment]
Sorry, we can't help you here. This a a bug tracker for Osmium. We do not provide binaries for any systems because we don't have them either.

**Comment by Jillinger** [comment]
@NiceStepUp this is quite late, so maybe you no longer need a solution,  as you might have found another tool. However, apparently you have to create a directory called osmium-tool in your projects folder. It is here, appveyor will create the build directory.
