### ISSUE TITLE
osmium-tool not showing progress?

### ISSUE THREAD

**Issue by mboeringa** [osmcode/osmium-tool#183]
Hi,

Just a small question: 

This is the first time I have tried using osmium using the osmium-tool version 1.10.0-1 as was available from the Synaptic package manager as bundled with my current Ubuntu 19.10 Eoan install on Virtualbox 6.1.

I wanted to extract all woodland polygons from a downloaded planet file according to the example command line as documented on the osmium-tool manual pages. However, once I clicked 'Enter' to start the process, no progress of any kind is displayed in the Terminal window.

Only after opening up the System Monitor, clicking the Processes TAB, and specifically choosing "My Processes", did I realize osmium was in fact running fine in the background and actively reading the planet file. 

Is this the expected behavior, or an issue with my system that no progress is being displayed?

![afbeelding](https://user-images.githubusercontent.com/7635726/73645036-cdbca900-4676-11ea-9e4c-2a7f734bbc56.png)

**Comment by mboeringa** [comment]
OK, I now see progress being displayed in the writing stage. It appears the tool first goes through a couple of reading cycles on the pbf file (the tags-filter selected both ways and relations as can be seen from the command line), and only then starts writing the resulting output file and display progress. 

Still, even if no real-time progress can be reasonably displayed for the reading stage, it might be nice to see some output message, like "Reading pbf file..." to indicate what is going one.

![afbeelding](https://user-images.githubusercontent.com/7635726/73650707-0ebaba80-4683-11ea-9b75-75e08a9951cf.png)

**Comment by joto** [comment]
Use `-v` or `--verbose` to see more output. It will tell you about each step.

As you noticed the progress display is only shown in some stages. This is not perfect, but it is not always easy to get this right. In this case (the `tags-filter` command) the file is read several times and it depends on the exact filter expressions used and the file contents how many times it must be read. And each pass throught the file reads only some information. All of this would make for a confusing display anyway, you would see the bar sometimes moving quickly, sometimes very slowly, not giving you a good idea how far it actually is. So I opted for this simpler display.

**Comment by mboeringa** [comment]
Hi @joto,

Thanks. Yes, I just noticed the `--verbose` option in the manual pages! This largely should solve the issue.

However, note that I am not suggesting you should enable some form of progress display for the reading phase, I fully appreciate that some processes cannot reasobly show real-time progress. 

Nonetheless, maybe showing a simple single-line message as I already suggested even in non-verbose mode (_"Reading pbf file..."_) would at least prevent some confusion for novice osmium-tool users like myself, and also prevent users from cancelling the command possibly thinking it got stuck somehow.

It now finished fine by the way ;-)

**Comment by joto** [comment]
Osmium follows the Unix tradition of not outputting anything as long as everything is fine. That's not always the easiest for beginners, but is really efficient once you get to know the tools.
