### ISSUE TITLE
"bus error (core dumped)" running 'osmium export'

### ISSUE THREAD

**Issue by worace** [osmcode/osmium-tool#184]
I'd appreciate any advice on how to further diagnose this issue.

I'm running the command:

```
osmium export --index-type sparse_file_array -c config.json --add-unique-id=type_id -f geojsonseq -x print_record_separator=false --verbose ~/data/osm/planet-latest.osm.pbf > /wdhdd/data/osm/admin_full_pass.geojsonseq
```

With the JSON config file:

```json
{
  "attributes": {
    "type":      false,
    "id":        true,
    "version":   false,
    "changeset": false,
    "timestamp": false,
    "uid":       false,
    "user":      false,
    "way_nodes": false
  },
  "linear_tags":  false,
  "area_tags":    false,
  "exclude_tags": [],
  "include_tags": ["admin_level", "border_type", "boundary=administrative", "place=country",
                   "place=state", "place=region", "place=city", "place=town", "place=suburb",
                   "ISO3166-1", "ISO3166-2"]
}
```

Here's the output from my process:

```
[ 0:00] Started osmium export
[ 0:00]   osmium version 1.11.1 (v1.7.1-301-g74cf303)
[ 0:00]   libosmium version 2.15.4
[ 0:00] Command line options and default settings:
[ 0:00]   input options:
[ 0:00]     file name: /home/horace/data/osm/planet-latest.osm.pbf
[ 0:00]     file format:
[ 0:00]   output options:
[ 0:00]     file name: -
[ 0:00]     file format: geojsonseq
[ 0:00]     overwrite: no
[ 0:00]     fsync: no
[ 0:00]   attributes:
[ 0:00]     type:      (omitted)
[ 0:00]     id:        @id
[ 0:00]     version:   (omitted)
[ 0:00]     changeset: (omitted)
[ 0:00]     timestamp: (omitted)
[ 0:00]     uid:       (omitted)
[ 0:00]     user:      (omitted)
[ 0:00]     way_nodes: (omitted)
[ 0:00]   output format options:
[ 0:00]     print_record_separator = false
[ 0:00]   linear tags: none
[ 0:00]   area tags:   none
[ 0:00]   include only these tags:
[ 0:00]     admin_level
[ 0:00]     border_type
[ 0:00]     boundary=administrative
[ 0:00]     place=country
[ 0:00]     place=state
[ 0:00]     place=region
[ 0:00]     place=city
[ 0:00]     place=town
[ 0:00]     place=suburb
[ 0:00]     ISO3166-1
[ 0:00]     ISO3166-2
[ 0:00]   other options:
[ 0:00]     index type: sparse_file_array
[ 0:00]     add unique IDs: type and id
[ 0:00]     keep untagged features: no
[ 0:00] First pass (of two) through input file (reading relations)...
[ 1:10] First pass done.
[ 1:10] Second pass (of two) through input file...
zsh: bus error (core dumped)  osmium export --index-type sparse_file_array -c config.json  -f geojsonseq -x
```

System is Ubuntu 18.04 on a Ryzen 3700x CPU with 32G of RAM.

My libosmium and osmium-tool were both built from source.

The process does successfully generate ~100k features in my output file before crashing.

There doesn't seem to be any more detailed stack trace besides that "bus error" message. Happy to provide more info if there is anything else I can look at.

**Comment by joto** [comment]
This almost certainly means you do not have enough RAM. Looks like you are processing a full planet, in that case `--index-type sparse_file_array` is definitely wrong, this will need much more memory than you have. Please read the `MEMORY USAGE` section in the man page and the `osmium-index-types` man page referenced there.

**Comment by worace** [comment]
Thanks for your response.

From reading the manual I thought that the purpose of the `*_file_*` index types was to alleviate the need to fit the full index in RAM:

> The second question is whether you have enough RAM to hold all the data in the index. Of course it is more efficient to keep the index in RAM, but if you don’t have enough, you need to use a disk-based index. The second component of the index type is either mem for in-memory storage or file for storage on disk.

Is that mistaken? I also noticed that I don't seem to be able to set the file location for the on-disk index, which I thought I remembered doing in the past:

> When using the file-based index types (*_file_array), add the filename you want to use for the index after a comma to the index types like so: ... -i dense_file_array,index.dat ...

However my version of osmium does not seem to accept that format:

```
Unknown index type 'dense_file_array,planet-osm-index.dat'. Use --show-index-types or -I to get a list.
```

**Comment by joto** [comment]
@worace Uh. Sorry, I didn't read that correctly. You are right, a file index should work on disk and not need that much memory. Still, you should use `dense_file_array` for the planet.

> However my version of osmium does not seem to accept that format:

Damn. I thought I had fixed that bug. But I fixed it in only one place and not the other... This is now fixed in master.

Maybe this is where your problem comes from: When you don't add a file name to `dense_file_array`  or `sparse_file_array` osmium will create a temporary file for you (usually in `/tmp`). If that directory is on a memory disk, you'll run out of memory.

**Comment by worace** [comment]
I see, that is good to know. I don't think my `/tmp` is on a ramdisk, but it's possible that disk was just filling up if the index was going there since I couldn't use the file path setting to put it on the second disk I am using for these large OSM files.

Do you think I would see the same error if `/tmp` was filling up regardless of whether it was ram or real disk?

I rebuilt my osmium-tool and now the `dense_file_array,/index-path` option is working. So hopefully that sorts it out.

Thanks for your help!

**Comment by joto** [comment]
I did some tests and it turns out that you get a bus error any time the index file is on a file system that is too small, even if it is a normal disk file system. The reason is that even with a file backing the memory mapping, Linux doesn't reserve the space on disk until it is used. 

This is difficult to work around. I am experimenting with checking the available space on the file system and failing if that will not be enough. But this is not perfect, something else could have written to the file system in the mean time etc.
