### ISSUE TITLE
When I used the osmium cut map, I found that some road were missing

### ISSUE THREAD

**Issue by zhangtiedong0912** [osmcode/osmium-tool#185]
When I used the osmium cut map, I found that some road were missing，The missing roads do not appear on the boundary, but on the inside. I found that these roads are of lower rank, but not all the lower rank roads are lost.

osmium extract -s smart -p ID.poly SEA.pbf -o ID.pbf --overwrite

**Comment by zhangtiedong0912** [comment]
![image](https://user-images.githubusercontent.com/51616101/79432090-edb90300-7ffd-11ea-8ff0-28170e925584.png)
the red is lost

**Comment by joto** [comment]
Can you give us the input files? Without them I can't debug what the problem might be.

**Comment by zhangtiedong0912** [comment]
sorry sir, i can't give you the original file ,Because it involves the company's privacy，but i will try to use osmium to cut the OSM file, If there are still such problems, I will feedback to you, thank you for your help

**Comment by joto** [comment]
If you are using files you generated yourself, chances are those file are not in a format that Osmium expects. Most likely they are a) not sorted correctly or b) not reference complete. Use `osmium fileinfo -e` and `osmium check-refs` to check your input files.

**Comment by zhangtiedong0912** [comment]
thank you sir let me try it

**Comment by zhaitianduo** [comment]
Hi @joto What kind of sort do we need to use osmium correctly? sort by id?

**Comment by zhangtiedong0912** [comment]
File:
  Name: /Users/tiedong.zhang/Downloads/otmap/SEA.pbf
  Format: PBF
  Compression: none
  Size: 4765737746
Header:
  Bounding boxes:
  With history: no
  Options:
    generator=0.47
    pbf_dense_nodes=true
[======================================================================] 100%
Data:
  Bounding box: (49.4389693,-13.741792,156.6583128,50.9547069)
  Timestamps:
    First: 2017-10-08T21:00:00Z
    Last: 2017-10-08T21:00:00Z
  Objects ordered (by type and id): yes
  Multiple versions of same object: no
  CRC32: not calculated (use --crc/-c to enable)
  Number of changesets: 0
  Number of nodes: 551065524
  Number of ways: 98548288
  Number of relations: 320348
  Smallest changeset ID: 0
  Smallest node ID: 695774
  Smallest way ID: 3049
  Smallest relation ID: 423
  Largest changeset ID: 0
  Largest node ID: 6677921835
  Largest way ID: 4000710374336001
  Largest relation ID: 10024540
  All objects have following metadata attributes: all
  Some objects have following metadata attributes: all
  Number of buffers: 1063287 (avg 611 objects per buffer)
  Sum of buffer sizes: 68307590176 (68.307 GB)
  Sum of buffer capacities: 69720932352 (69.72 GB, 98% full)
[21:27:41 tiedong.zhang:~/Downloads/otmap]$ osmium check-refs /Users/tiedong.zhang/Downloads/otmap/SEA.pbf
[======================================================================] 100%
There are 551065524 nodes, 98548288 ways, and 320348 relations in this file.
Nodes in ways missing: 0

**Comment by zhangtiedong0912** [comment]
@joto  hi sir , could you please help me check the file info

**Comment by joto** [comment]
This looks okay to me so far. Please try also `osmium check-refs -r`.

**Comment by zhangtiedong0912** [comment]
@joto  hi jojo do you know how to control the use of memory when we use osmium?

**Comment by zhangtiedong0912** [comment]
I need to cut Indonesia from the entire PBF of southeast Asia with a ploy file

**Comment by joto** [comment]
Please don't reopen existing issues for unrelated topics, create new issues for new topics instead.

On the topic of memory the man pages have sections about memory usage. Also read the `index-types` help. But generally the answer to your question is: You need the memory you need, there isn't much you can do about it.

**Comment by zhangtiedong0912** [comment]
thank you sir
