### ISSUE TITLE
[Q] osmium extract config file

### ISSUE THREAD

**Issue by dooley** [osmcode/osmium-tool#187]
What is equivalent to 
`--output-header=osmosis_replication_timestamp!`
in a config file? Can this be done?

The config below throw an error
> can not parse timestamp: 'osmosis_replication_timestamp!'

`{
  "directory": "/osm_data",
  "extracts": [
    {
      "output": "berlin.osm.pbf",
      "output_header": {
        "osmosis_replication_timestamp": "osmosis_replication_timestamp!"
      },     
      "multipolygon": {
          "file_name": "berlin.poly"
      }
    }
  ]
}`

osmium is:
> osmium version 1.12.0 (v1.12.0)
> libosmium version 2.15.5

**Comment by joto** [comment]
This is currently not possible. The header setting in the config file doesn't support the special `!` syntax. So for the moment you have to set this on the command line.

But this is a clear inconsistency in the code, thanks for reporting this. I have to think about how to best fix this.

**Comment by dooley** [comment]
Thank you. Would be a nice, if we can set them too in the config.

**Comment by joto** [comment]
It is now possible to set something like `"output_header": { "osmosis_replication_timestamp": null }, ...`. in the config file to tell osmium to use the setting from the input file.
