### ISSUE TITLE
Osmium-Tool Missing 'tags-filter' Function

### ISSUE THREAD

**Issue by Luedkejj** [osmcode/osmium-tool#188]
I downloaded osmium-tool through my command line using apt-get, and it appears that the osmium-tool I downloaded is missing some features, specifically the 'tags-filter' function. I tried calling the function and osmium-tool did not recognize the command. I ran the help command and 'tags-filter' did not show up on the commands list. Did I download an old version of osmium-tool? Has anyone run into this issue before?

**Comment by Nakaner** [comment]
Which version did you install? You can check this with `dpkg -l | grep osmium-tool`. Are you sure that the `tags-filter` command was added before or at that release? Please compare with the [changelog](https://github.com/osmcode/osmium-tool/blob/master/CHANGELOG.md).

It would be very nice and very helpful if bug reports contained some basic information such as:

* operation system
* version of the software
* the error message/the output of the software not working as expected
* how you called the programme (command line including all options)
* not here but often useful: input files to reproduce the issue

**Comment by joto** [comment]
Most likely you just have an old version of osmium in your distro's package. Use `osmium version` to check it.

If you are using Debian, see https://backports.debian.org/ for a solution. Otherwise you will have to compile a current version of Osmium yourself.
