### ISSUE TITLE
Remove nodes not referenced in any way/relation?

### ISSUE THREAD

**Issue by jcoupey** [osmcode/osmium-tool#189]
It's often useful to remove some objects from OSM files before feeding them to another tool in order to speed-up subsequent treatments.

For example the last command at https://osmcode.org/osmium-tool/manual.html#filtering-by-tags shows how to remove all ways with a `building` tag:

```
osmium tags-filter -i city.osm.pbf wr/building -o no-buildings.osm.pbf
```

This effectively drops all ways describing buildings but leaves all the nodes in the extract. I get it this is expected behaviour, but in the case a node is not used in any other (kept) way, I'd like to have it removed too.

So my question comes down to: is there a built-in process (or sequence of filtering steps) that would remove all nodes in an OSM extract that are not members of any existing way or relation?

PS: I've read with interest https://blog.jochentopf.com/2016-04-20-node-locations-on-ways.html on ways with self-contained node locations. Unfortunately this won't be sufficient for the use-case I have in mind because I still want to do a per-node processing step down the line.

**Comment by joto** [comment]
1. Filter out exactly what you want creating `filtered_file.osm.pbf`
2. Run `osmium getid --add-referenced --id-osm-file=filtered_file.osm.pbf original_input.osm.pbf`

The result wil be exactly what you wanted plus all referenced objects. Depending on what you want to do you might also want to use `--remove-tags` on `getid`.

**Comment by jcoupey** [comment]
Thanks, the `osmium getid` command is definitely what I was missing.

I have a follow-up question on step 1: it's straightforward if I know exactly what I want  to keep, but my understanding is that if I want to stick to an inverted filter approach (e.g. `osmium tags-filter -i wr/building`), then I also need to get rid of all nodes so that only referenced nodes are added at step 2. 

I did not find an easy way to do this automatically. I've tried adding `n/` or `n/*` to the `osmium tags-filter -i` command, to no avail. What would be the simplest way to achieve this?

**Comment by joto** [comment]
Please have a look at the man pages of all the commands and their options and you'll find some ideas.
`--omit-referenced` for `osmium getid` and `--object-type` on `osmium cat` look promising to puzzle something together.

**Comment by jcoupey** [comment]
Thanks for the pointer to `--omit-referenced`, I should indeed have dug myself in the `tags-filter` man page.

For the record if anyone ever comes across this ticket, I ended up doing something like this, based on the above filtering example:

```
osmium tags-filter -i city.osm.pbf wr/building --omit-referenced -o required_wr.osm.pbf
osmium getid --add-referenced --remove-tags --id-osm-file=required_wr.osm.pbf city.osm.pbf -o city_filtered.osm.pbf
```
