### ISSUE TITLE
Different behaviour between 1.7.1 and 1.11.1

### ISSUE THREAD

**Issue by jcoupey** [osmcode/osmium-tool#190]
I've been using `v1.7.1` to test a workflow that removes all ways and relations describing buildings, then drops all nodes that are not referenced any more in any of the remaining way or relation (see #189). A sample test script is as follows:

```
wget http://download.geofabrik.de/europe/monaco-200618.osm.pbf
osmium tags-filter -v -i monaco-200618.osm.pbf wr/building --omit-referenced -o required_wr.osm.pbf
osmium getid -v --add-referenced --id-osm-file=required_wr.osm.pbf monaco-200618.osm.pbf -o monaco-200618_filtered.osm.pbf
osmium diff monaco-200618.osm.pbf monaco-200618_filtered.osm.pbf | grep '^-n' | wc -l
```

The last command outputs `9122`, which stands for the number of nodes that have been removed in the process.

Now if I perform the exact same steps on another box running `v1.11.1`, then the last command outputs `0` so the filtered extract contains the same number of nodes than the original extract. The number of removed ways and relations is identical with both versions.

I went through the changelog but did not spot anything suggesting a change in behaviour for those commands, I'm I missing something here?

**Comment by joto** [comment]
The new behaviour is correct. You should have all nodes, because your filter expression isn't asking for any nodes and you are using `-i`.

**Comment by jcoupey** [comment]
Thanks for the clarification. So I added an `osmium cat -t way -t relation` step to get rid of the nodes (I did not understand when you mentioned it back in #189 because it was indeed not necessary on `v1.7.1`).
