### ISSUE TITLE
Memory issue for Renumber after merging few separate osm.obf files

### ISSUE THREAD

**Issue by toton6868** [osmcode/osmium-tool#191]
I am trying to merge 6-7 countries. After successfully merging it became 1.57 GB only. Then I tried the `osmium renumber` but it is showing 

> Out of memory. Read the MEMORY USAGE section of the osmium(1) manpage.

I am using 16 GB RAM machine. What should I do?

Thanks

**Comment by joto** [comment]
Did you "Read the MEMORY USAGE section of the osmium(1) manpage."?

**Comment by toton6868** [comment]
@joto ... Sorry My 12 GB memory was using by another process. I forget to delete this issue. Really Sorry.
