### ISSUE TITLE
Extract and delete OSM Data with certain polygons?

### ISSUE THREAD

**Issue by pcace** [osmcode/osmium-tool#192]
Hi,

i dont know if i am at the right place here to ask questions. So please delete if this is not the right place!

So my question is, is it possible to use osmium-tool to delete OSM data within gpx polygons? To be more precise, i have a couple houndred polygons on a map and want to delete all OSM data inside of these gpx polygons. Is this somehow possible with the tool? 

Tank you so much,

Pcace

**Comment by joto** [comment]
You can use `osmium extract` to create an extract of an OSM file which contains some part of the input data based on the geometry. If you'd be able to create a multipolygon from your GPX files that contains the boundaries of those GPX files as inner rings, you could use osmium to extract everything but whatever is in the gpx polygons. But how to create those boundary polygons goes way beyond what we can cover here. I suggest https://gis.stackexchange.com/
