### ISSUE TITLE
add-locations-to-ways not working with negative node ids

### ISSUE THREAD

**Issue by halkoma** [osmcode/osmium-tool#193]
Lat and lon not copied to the nd refs of ways when the nodes have a negative id. Intended or not? Anyway, OSM allows negative node ids which can be used when experimenting.

`osmium add-locations-to-ways -n --overwrite --ignore-missing-nodes input.osm -o output.osm`

Example output.osm, starting with node id 1 and decrementing:
```
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmium/1.11.1">
  <node id="1" version="1" lat="xx.xxxxxxx" lon="yy.yyyyyyy"/>
  <node id="0" version="1" lat="xx.xxxxxxx" lon="yy.yyyyyyy/>
  <node id="-1" version="1" lat="xx.xxxxxxx" lon="yy.yyyyyyy"/>
  <way id="-1" version="1">
    <nd ref="1" lat="xx.xxxxxxx" lon="yy.yyyyyyy"/>
    <nd ref="0" lat="xx.xxxxxxx" lon="yy.yyyyyyy/>
    <nd ref="-1"/>       <!--NO LAT AND LON HERE-->
  </way>
</osm>
```

**Comment by joto** [comment]
This was an oversight. Should work now.
