### ISSUE TITLE
Unexpected differences when running osmium-diff

### ISSUE THREAD

**Issue by mlabrec** [osmcode/osmium-tool#195]
I am running osmium-diff to diff two planet files and am seeing some unexpected output.

Steps:

1. Download 2020-07-20 planet file
```
$ mkdir osmium-test
$ cd osmium-test
$ wget https://planet.openstreetmap.org/pbf/planet-200720.osm.pbf
```

2. Download daily replication files from 2020-07-20 through 2020-07-27
```
$ wget https://planet.openstreetmap.org/replication/day/000/002/868.osc.gz
$ wget https://planet.openstreetmap.org/replication/day/000/002/869.osc.gz
$ wget https://planet.openstreetmap.org/replication/day/000/002/870.osc.gz
$ wget https://planet.openstreetmap.org/replication/day/000/002/871.osc.gz
$ wget https://planet.openstreetmap.org/replication/day/000/002/872.osc.gz
$ wget https://planet.openstreetmap.org/replication/day/000/002/873.osc.gz
$ wget https://planet.openstreetmap.org/replication/day/000/002/874.osc.gz
$ wget https://planet.openstreetmap.org/replication/day/000/002/875.osc.gz
```

3. Apply daily replication files to 2020-07-20 planet file in order to update it to 2020-07-27.
```
$ osmium apply-changes planet-200720.osm.pbf *.osc.gz --output manual-planet-200727.osm.pbf
```
4. Download 2020-07-27 planet file
```
$ wget https://planet.openstreetmap.org/pbf/planet-200727.osm.pbf
```

5. Diff the manually constructed 2020-07-27 planet file and the official 2020-07-27 planet file.
```
$ osmium diff manual-planet-200727.osm.pbf planet-200727.osm.pbf --suppress-common --output-format debug --output diff
```

Expected:
No output reported in the diff file, aside from potential element differences during the small time offset between the daily replication files and the planet files (osmium-fileinfo for the 2020-07-27 planet file shows it has a timestamp of "2020-07-26T23:59:56Z", while the state.txt file for the 2020-07-27 daily replication file displays a timestamp of "2020-07-27T00:00:00Z").

Actual:
Many differences are reported for reasons of (1) tag order differences and (2) username differences.

1. Tag order differences

One example is node 116028:
```
-node 116028 visible
-  version:   4
-  changeset: 88515182
-  timestamp: 2020-07-26T09:13:54Z (1595754834)
-  user:      340741 "CRCulver"
-  lon/lat:   25.8169979,66.5419255
-  tags:      2
-    "crossing" = "uncontrolled"
-    "highway"  = "crossing"

+node 116028 visible
+  version:   4
+  changeset: 88515182
+  timestamp: 2020-07-26T09:13:54Z (1595754834)
+  user:      340741 "CRCulver"
+  lon/lat:   25.8169979,66.5419255
+  tags:      2
+    "highway"  = "crossing"
+    "crossing" = "uncontrolled"```
```

In the above difference, everything is identical for the node except for the tag order. I notice that all cases where the tag order is different are for elements which are modified by one of the daily replication files which were applied in step 2. The planet files appear to use one tag order, while the replication files use another tag order.

2. Username differences

One example is node 10769147:
```
-node 10769147 visible
-  version:   4
-  changeset: 80429914
-  timestamp: 2020-02-02T09:48:44Z (1580636924)
-  user:      4498213 "Spotter Cluster"
-  lon/lat:   14.3243469,48.8111656

+node 10769147 visible
+  version:   4
+  changeset: 80429914
+  timestamp: 2020-02-02T09:48:44Z (1580636924)
+  user:      4498213 "Jiří Podhorecký"
+  lon/lat:   14.3243469,48.8111656
```

The node is identical in both entries aside from the username. The user ID is the same, and it appears to be the case that the user changed their username. Since OSM does not send replication updates for username changes, it seems the username differences are actually expected.

Some questions I had are:

1. Why does osmium-diff report differences when tag order is different? It does not seem OSM itself respects tag order.
2. Is there a way to ignore tag order differences with osmium-diff?
3. Is there a way to ignore username differences with osmium-diff? While it seems as though the username differences between the files are legitimate, it would be useful to be able to fully diff the other fields without the noise caused by users changing their username.

I am aware that ```derive-changes``` can be used to diff elements just based on type, ID, and version, which could be used to filter out the issues mentioned above. But, given that this only partially diffs the data (e.g., tags could be completely wrong in one file and no change would be reported), it does not work for my use case.

Thank you

**Comment by joto** [comment]
While nobody ever wrote down any guarantees, tags in OSM files are basically always ordered. (This is precisely because it makes the kinds of things you are doing here possible.) It seems this isn't the case any more in newer planet files. This needs to be investigated.

Users changing there user name doesn't happen that often, so the issue has never come up. There is currently no way to ignore some changes, but I'll consider adding it. As a workaround you can use the `--clean` option on `osmium cat` to remove the uid/user name entirely on both files and then compare them.

**Comment by joto** [comment]
Hm. Apparently I was wrong. Older planet files also have unordered tags. But I have done the same kind of thing you have done and never had these kinds of problems. So maybe what changed recently was only that the dump and the diff have different order and that never was the case before.

**Comment by mlabrec** [comment]
Thanks, the clean option looks like it will work well for me, as I can just remove the username field and still compare everything else. I don't find this option on the documentation here https://docs.osmcode.org/osmium/latest/osmium-cat.html. Is this the latest documentation? I do find the option here https://manpages.debian.org/unstable/osmium-tool/osmium-cat.1.en.html.

Being able to directly ignore fields with osmium-diff would also be useful. In terms of the frequency of username changes, from a planet file from just ~2 months ago there are over 6 million differences from the latest planet caused by username changes.
