### ISSUE TITLE
osmium::Object PointerCollection’ has no member named ‘ptr_begin’

### ISSUE THREAD

**Issue by jaigsingla** [osmcode/osmium-tool#198]
Hi, Libosmium built successfully .
facing issue in building osmium tool. 

[ 20%] Built target man
[ 21%] Building CXX object src/CMakeFiles/osmium.dir/command_apply_changes.cpp.o
In file included from /usr/local/include/osmium/tags/matcher.hpp:37:0,
                 from /home/deep/osmium/osmium-tool-master/src/util.hpp:30,
                 from /home/deep/osmium/osmium-tool-master/src/command_apply_changes.cpp:25:
/usr/local/include/osmium/util/string_matcher.hpp:57:77: note: #pragma message: Disabling regex functionality. See source code for info.
 #  pragma message("Disabling regex functionality. See source code for info.")
                                                                             ^
In file included from /home/deep/osmium/osmium-tool-master/src/command_apply_changes.cpp:45:0:
/home/deep/osmium/boost_1_74_0/boost/function_output_iterator.hpp:14:102: note: #pragma message: This header is deprecated. Use <boost/iterator/function_output_iterator.hpp> instead.
 BOOST_HEADER_DEPRECATED("<boost/iterator/function_output_iterator.hpp>")
                                                                                                      ^
/home/deep/osmium/osmium-tool-master/src/command_apply_changes.cpp: In member function ‘virtual bool CommandApplyChanges::run()’:
/home/deep/osmium/osmium-tool-master/src/command_apply_changes.cpp:280:30: error: ‘class osmium::ObjectPointerCollection’ has no member named ‘ptr_begin’
         std::reverse(objects.ptr_begin(), objects.ptr_end());
                              ^
/home/deep/osmium/osmium-tool-master/src/command_apply_changes.cpp:280:51: error: ‘class osmium::ObjectPointerCollection’ has no member named ‘ptr_end’
         std::reverse(objects.ptr_begin(), objects.ptr_end());

**Comment by joto** [comment]
Well, did you look at the source code? A quick search would have revealed this:

```
// std::regex isn't implemented properly in glibc++ (before the version
// delivered with GCC 4.9) and libc++ before the version 3.6, so the use is
// disabled by these checks. Checks for GLIBC were based on
// https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions
// Checks for libc++ are simply based on compiler defines. This is probably
// not optimal but seems to work for now.
```

So most likely your system is too old.

**Comment by jaigsingla** [comment]
https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions

output on my machine :
st|mt|tr matches st? 1
st|mt|tr matches mt? 1
st|mt|tr matches tr? 1

**Comment by jaigsingla** [comment]
[ 41%] Building CXX object src/CMakeFiles/osmium.dir/command_apply_changes.cpp.o
/home/deep/osmium/osmium-tool-master/src/command_apply_changes.cpp: In member function ‘virtual bool CommandApplyChanges::run()’:
/home/deep/osmium/osmium-tool-master/src/command_apply_changes.cpp:280:30: error: ‘class osmium::ObjectPointerCollection’ has no member named ‘ptr_begin’; did you mean ‘begin’?
         std::reverse(objects.ptr_begin(), objects.ptr_end());
                              ^~~~~~~~~
                              begin
/home/deep/osmium/osmium-tool-master/src/command_apply_changes.cpp:280:51: error: ‘class osmium::ObjectPointerCollection’ has no member named ‘ptr_end’
         std::reverse(objects.ptr_begin(), objects.ptr_end());
                                                   ^~~~~~~
make[2]: *** [src/CMakeFiles/osmium.dir/command_apply_changes.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/osmium.dir/all] Error 2

**Comment by jaigsingla** [comment]
Issue of class member is still found.

**Comment by jaigsingla** [comment]
Hello Joto,
What is your suggestion ??

**Comment by joto** [comment]
@jaigsingla You do realize that you are using a free product and I am doing this in my free time, do you? And that this here is really a place to report bugs with osmium-tool, not a help line? Pushing like this is rude and not likely going to make me interested in helping you.

If you want to get help, start by separating out different problems into different github issues. And describe exactly what you have been doing, what you expected to happen and what happened instead. Include all relevant information such as command lines, full output, software versions used etc. Having a jumble of snippets like above is making it really hard for me to even understand what you are doing.

That being said the problem with `ptr_begin` looks like you are using the master version of `osmium-tool`. You should not use unreleased versions of any software unless you know what you are doing, use a released version. The `osmium-tool` master needs `libosmium` master to work.
