### ISSUE TITLE
osmium extract related

### ISSUE THREAD

**Issue by jaigsingla** [osmcode/osmium-tool#199]
Hi,

I am using osmium extract -b 22.98,72.5,23.06,72.59 on india-latest.osm.pbf -o amd.osm.pbf  

It completes successfully but 94 Byte amd.osm.pbf file is generated  and no information is present in the file.

**Comment by joto** [comment]
You probably mixed up the coordinates.

**Comment by jaigsingla** [comment]
Right . Its long1,lat1, long2,lat2 format.
