### ISSUE TITLE
utf8.h No Such File or Directory

### ISSUE THREAD

**Issue by RyanRosario** [osmcode/osmium-tool#20]
I am not sure if this is a problem with libosmium, or with osmium-tool. Build, installation and unit tests for libosmium (2.5.3) were all successful. When I try to build osmium-tool (both from GitHub, and also the latest release) on Ubuntu 14.04LTS I get the following error:

cmake .
make
[ 29%] Built target man
[ 29%] Building CXX object test/CMakeFiles/unit_tests.dir/__/src/command_cat.cpp.o
In file included from /usr/local/include/osmium/io/detail/output_format.hpp:45:0,
                 from /usr/local/include/osmium/io/writer.hpp:45,
                 from /usr/local/include/osmium/io/debug_output.hpp:36,
                 from /usr/local/include/osmium/io/any_output.hpp:48,
                 from /home/ryan/Documents/Software/osmium-tool/src/command_cat.cpp:29:
/usr/local/include/osmium/io/detail/string_util.hpp:42:18: fatal error: utf8.h: No such file or directory
 #include <utf8.h>
                  ^
compilation terminated.
make[2]: *** [test/CMakeFiles/unit_tests.dir/__/src/command_cat.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/unit_tests.dir/all] Error 2
make: *** [all] Error 2

I have libicu and libicu-dev installed on my system.

**Comment by joto** [comment]
You don't have utfcpp installed. This was mentioned in the README, but missing from the installation info on https://github.com/osmcode/libosmium/wiki/Libosmium-dependencies . I have added the information there. Short answer for you: Install `libutfcpp-dev` Ubuntu package.

**Comment by RyanRosario** [comment]
Awesome! Thanks!
