### ISSUE TITLE
Decrecated header warning when using Boost 1.74

### ISSUE THREAD

**Issue by sphoto** [osmcode/osmium-tool#202]
Occurs while building .obj from `command_apply_changes.cpp`

 ```
D:\projects\boost_1_74_0\boost/function_output_iterator.hpp(14): note: This header is deprecated. Use <boost/iterator
  /function_output_iterator.hpp> instead.
```

**Comment by joto** [comment]
Thanks for the report. We support boost versions far enough back that the old header name was still the correct one, so we can't change this yet.
