### ISSUE TITLE
Required libosmium 2.15.6 not sufficient to build osmium tool

### ISSUE THREAD

**Issue by sphoto** [osmcode/osmium-tool#204]
You should change the requirements to build osmium tool. Up to now you check against libosmium 2.15.6. But a later commit 
[be04b4d](https://github.com/osmcode/libosmium/commit/be04b4d58b4ad0036dae12bf2af114b833675dd1) is needed, since `ptr_begin()/ptr_end()` are used in `command_apply_changes.cpp` and `command_merge_changes.cpp`

**Comment by joto** [comment]
I am aware of that, but I can't depend on a version that isn't released yet. So for the time being this is just something that people using master have to live with.

**Comment by joto** [comment]
Fixed now that libosmium 2.16.0 is released.
