### ISSUE TITLE
Index type behaviour

### ISSUE THREAD

**Issue by thomersch** [osmcode/osmium-tool#207]
Either I don't understand index types at all or there might be some bug with the selection of the index type for `export` and `add-locations-to-ways`:

I ran

    osmium add-locations-to-ways -i dense_file_array,/tmp/osmium.dat -v -o planet-latest-with-nodes.osm.pbf planet-latest.osm.pbf

Which in the verbose output gives me

    index type (for positive ids): dense_file_array,/tmp/osmium.dat 

But it still eats memory like Java: 
<img width="910" alt="Screenshot 2021-02-15 at 10 00 51" src="https://user-images.githubusercontent.com/948605/107932126-7cc7dc00-6f7d-11eb-952c-ea4d03ff8407.png">

Also, it wrote the `/tmp/osmium.dat` file, totalling at 63G, but didn't seem to seek in it:

```
# procstat files 11972                                                                                                    
  PID COMM                FD T V FLAGS    REF  OFFSET PRO NAME                                                                            
11972 osmium            text v r r-------   -       - -   /usr/local/bin/osmium                                                           
11972 osmium            ctty v c rw------   -       - -   /dev/pts/1                                                                      
11972 osmium             cwd v d r-------   -       - -   /tmp                                                                            
11972 osmium            root v d r-------   -       - -   /                                                                               
11972 osmium               0 v c rw------  22   11728 -   /dev/pts/1                                                                      
11972 osmium               1 v c rw------  22   11728 -   /dev/pts/1                                                                      
11972 osmium               2 v c rw------  22   11728 -   /dev/pts/1                                                                      
11972 osmium               3 v r rw------   1       0 -   /tmp/osmium.dat                                                                 
11972 osmium               4 v r r-------   1 56137613312 -   /tmp/planet-latest.osm.pbf
11972 osmium               5 v r -w------   1 45023218364 -   /tmp/planet-latest-with-nodes.osm.pbf
```

Now, if I run with `-i none` it tells me:

    $ osmium export -i none -v -f spaten /tmp/planet-latest-with-nodes.osm.pbf
    Unknown index type 'none'. Use --show-index-types or -I to get a list.

```
$ osmium export --show-index-types
dense_file_array
dense_mem_array
flex_mem
sparse_file_array
sparse_mem_array
sparse_mem_map
none
```

Same issue on Linux with osmium/1.12.1 & libosmium/2.15.6 as well as FreeBSD with osmium/1.13.1 & libosmium/2.16.0.

For the record, /tmp is not a tmpfs.

**Comment by joto** [comment]
Osmium `mmap`s the index file into memory, so this will show up as memory used, but it doesn't mean you actually need that much RAM. The kernel will "magically" read the files contents from disk whenever it needs a part of it that is not in main memory. That's why you don't see seeks, or read or write system calls for that matter.

That `-i none` is not working is a bug. I'll look into that.

**Comment by thomersch** [comment]
> That -i none is not working is a bug. I'll look into that.

Thanks!

> Osmium mmaps the index file into memory, so this will show up as memory used, but it doesn't mean you actually need that much RAM. The kernel will "magically" read the files contents from disk whenever it needs a part of it that is not in main memory. That's why you don't see seeks, or read or write system calls for that matter.

In practice I wasn't able to get it to work on any memory-constrained system. I tried running `add-locations-to-ways` for a planet on a machine with 16 GB of RAM with NVMe-based cache and it takes several days. Imposm, which uses leveldb for on-disk caching, which should much more inefficient, needs just a small fraction of that time.
