### ISSUE TITLE
Cannot get merge to read from stdin

### ISSUE THREAD

**Issue by flowrean** [osmcode/osmium-tool#211]
Hi,
The documentation for the merge command says:

> This commands reads its input file(s) only once and writes its output file in one go so it can be streamed, ie. it can read from STDIN and write to STDOUT.

But I don't manage to achieve reading from stdin. (Except when only trying to merge a single file, but that's a trivial case.)

These commands should make it clear:
```shell
% cat n123477.osm 
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmium/1.13.1">
  <node id="123477" version="9" lat="51.2387484" lon="4.0609398"/>
</osm>

% cat n123478.osm
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmium/1.13.1">
  <node id="123478" version="11" lat="51.2446181" lon="4.0633105"/>
</osm>

# This works as expected (no use of stdin here).
% osmium merge n123477.osm n123478.osm -F osm -f osm            
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmium/1.13.1">
  <node id="123477" version="9" lat="51.2387484" lon="4.0609398"/>
  <node id="123478" version="11" lat="51.2446181" lon="4.0633105"/>
</osm>

# Trying to use stdin, but failing.
% cat n123477.osm | osmium merge - n123478.osm -F osm -f osm            
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmium/1.13.1">
</osm>
Could not get file size of file '': No such file or directory
```

Does the error arise because stdin is only supported when it's the only input? When omitting the `-`, stdin is ignored.

The same holds for the `cat` subcommand.

I am on macOS 11 with Osmium 1.13.1. Also tried with 1.8.0 and it gives the same result.

**Comment by flowrean** [comment]
I found a way to solve this, providing `/dev/stdin` instead of `-` as filename. But I will leave the issue open for the time being, as I believe `-` is more commonly used in a context like this.

**Comment by joto** [comment]
Thanks for the report, this is definitly a bug that needs fixing.

**Comment by flowrean** [comment]
OK. Unfortunately, I won't be of much help fixing this, as I don't have any experience with C++.

**Comment by joto** [comment]
This should be fixed now in master.
