### ISSUE TITLE
Hi, i can not build  when i run "cmake ..",how can i deal with this problem? Thanks

### ISSUE THREAD

**Issue by olongfen** [osmcode/osmium-tool#212]
CMake Error at /usr/local/lib/cmake/Boost-1.76.0/BoostConfig.cmake:240 (if):
  if given arguments:

    "ALL" "IN_LIST" "Boost_FIND_COMPONENTS"

  Unknown arguments specified
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:177 (find_package)
  CMakeLists.txt:46 (find_package)

**Comment by joto** [comment]
Doesn't look like this has anything to do with Osmium.
