### ISSUE TITLE
tags-filter ignores OSMIUM_POOL_THREADS

### ISSUE THREAD

**Issue by yvecai** [osmcode/osmium-tool#213]
It seems to me that the OSMIUM_POOL_THREADS environment variable has no influence on osmium tags-filter.

**Comment by joto** [comment]
What exactly did you do? What did you expect would happen? What happened instead? Which version of osmium-tool/libosmium did you use?

**Comment by yvecai** [comment]
Sorry for the late reply.
Libosmium manual describe OSMIUM_POOL_THREADS as "The number of threads in the thread pool used for certain input/output operations."
Setting this environment variable to reduce the load has no influence on osmium tags-filter, it uses as many core available but 2.

**Comment by joto** [comment]
This works fine for me. Again: Please describe **exactly** what you are doing, maybe we can figure out then what your problem is. But I can't guess from your description.

**Comment by yvecai** [comment]
My bad, reproducing to give more feedback, I figured out I had set the environment variable as the wrong user.
Indeed it works !
