### ISSUE TITLE
osmium extract performance

### ISSUE THREAD

**Issue by yanchenko-igor** [osmcode/osmium-tool#214]
Hello, my goal is to split planet file into smaller files, I noticed a strange behavior, I tried to extract Germany from a planet file and from already extracted Europe file, and extracting Germany from planet works faster, I moved forward with my experiment and ran three different tests.

```
osmium extract -v -b 11.35,48.05,11.73,48.25 planet-latest.osm.pbf -o munich_from_planet.osm.pbf
osmium extract -v -b 11.35,48.05,11.73,48.25 europe.osm.pbf -o munich_from_europe.osm.pbf
osmium extract -v -b 11.35,48.05,11.73,48.25 germany.osm.pbf -o munich_from_germany.osm.pbf
```
and results were 21 minutes for the planet file, 31 minutes for the europe file and 4,5 minutes for the germany file. It confuses me, when extracting from europe takes longer, is there a way to optimize it? or maybe a way to predict what file is going to be faster as a source?

**Comment by joto** [comment]
I can not reproduce this and it seems a bit unlikely given that there is strictly more work to do the larger the input file is. There are different ways to encode PBF files internally, so depending on where those input files came from and how they have been created there might be differences there but I don't think they would produce such large differences.

On what hardware are you running those numbers? Are you running this on real hardware with local disks with nothing else running? Did you run this multiple times and get consistent numbers?

**Comment by yanchenko-igor** [comment]
I am running on real hardware with SSD disks, yes I got those numbers multiple times in different order, and there are no heavy processes running. Let me download the files again, and I will describe how to reproduce it step by step.

**Comment by joto** [comment]
Hm, strange. Are the three `munich_from_...` files identical? (You can run `osmium fileinfo -c -e -g data.crc32 FILE` to get the checksum of each of them to check.)

What version of osmium/libosmium are you using?

**Comment by yanchenko-igor** [comment]
I am using this planet file https://planet.openstreetmap.org/pbf/planet-210419.osm.pbf
and I tried different europe files, extracted myself and from here https://download.geofabrik.de/europe-latest.osm.pbf 

The command you provides the same hash for all three files 2f3369c8

**Comment by yanchenko-igor** [comment]
osmium --version
osmium version 1.13.1 (v1.13.1-12-g98a7a34)
libosmium version 2.17.0

**Comment by mmd-osm** [comment]
Did you run osmium extract in different directories? Otherwise existing target osm.pbf would not be overwritten due to the missing "--overwrite" parameter in the command line.

I find it unlikely that the hashes are matching. The Geofabrik you've quoted doesn't include any metadata like user names or uids, unlike the planet file which includes all those details. To have a level playing field you would have at least to compare https://osm-internal.download.geofabrik.de/europe-latest-internal.osm.pbf with the planet pbf file.

**Comment by yanchenko-igor** [comment]
> Did you run osmium extract in different directories? Otherwise existing target osm.pbf would not be overwritten due to the missing "--overwrite" parameter in the command line.
I the target files are different in every case.


> 
> I find it unlikely that the hashes are matching. The Geofabrik download link you've provided doesn't include any real metadata values for fields like user names or uid, unlike the planet file. To have a level playing field, you would at least have to compare https://osm-internal.download.geofabrik.de/europe-latest-internal.osm.pbf with the planet pbf file.
I was not using the file from geofabrik, I used the europe file that I extracted from the planet, I said that the time is reproducible also with geofabric file, of course the hash will be different, if I use it.

**Comment by yanchenko-igor** [comment]
The server has 24 cores and 48G of memory, I attached the log file with all outputs.

[split.log](https://github.com/osmcode/osmium-tool/files/6451654/split.log)

**Comment by joto** [comment]
When I try the same thing (on a machine with 12 cores and 128GB memory), the planet->muc runs in 5:47, the planet->eu in 13:44 and the eu->muc in 2:56. That's much faster than anything you got. Did you, by any chance, compile osmium in debug mode without optimizations? Or how fast are your CPUs?

Just in case the large number of cores are problematic for some reason (I don't know why they should be but I have never tried it on a machine with that many cores), you can run with environment variable `OSMIUM_POOL_THREADS` set to, say, `8`?

**Comment by yanchenko-igor** [comment]
@joto Could you show your output so maybe I notice something different from my output? 

this is part of my build script 
```
 ...
 && git clone https://github.com/osmcode/libosmium.git \
 && cd libosmium \
 && mkdir build \
 && cd build \
 && cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_EXAMPLES=OFF .. \
 && make \
 && cd /home/renderer/src \
 && git clone https://github.com/osmcode/osmium-tool \
 && cd osmium-tool \
 && mkdir build \
 && cd build \
 && cmake -DCMAKE_BUILD_TYPE=MinSizeRel .. \
 && make \
 && make install \
 ...
```
The CPU is 3GHz fast.

I will try with the environment variable and let you know.

**Comment by yanchenko-igor** [comment]
> Okay, the `DCMAKE_BUILD_TYPE=MinSizeRel` explains at least some of the performance loss compared to a `Release` build which I would recommend. But it does not explain the planet vs. europe performance.

I rebuilt the app with suggested option, it slightly improved the performance for planet case and for germany case, but it is still slow for europe file.

- planet 19:48
- europe 31:17
- germany 4:15

**Comment by mmd-osm** [comment]
Have you tried this already?

> you can run with environment variable OSMIUM_POOL_THREADS set to, say, 8?

**Comment by yanchenko-igor** [comment]
> Have you tried this already?
> 
> > you can run with environment variable OSMIUM_POOL_THREADS set to, say, 8?

It doesn't make any significant difference.

**Comment by joto** [comment]
Can you try `osmium cat FILE -f blackhole` for all the files and see how long these will take? This will copy each file to "nowhere", essentially just reading the file. If we see the same pattern, we know it must have something to do with reading the file, if not, it must be something specific to the extract command.

**Comment by joto** [comment]
Thanks. Can you try to copy the planet file using `osmium cat /data/planet-latest.osm.pbf -o planet-copy.osm.pbf` and then do the `osmium cat planet-copy.osm.pbf -f blackhole`?

The only difference I can think of with the planet vs the europe file is that the original planet was encoded not by the osmium you have running but you downloaded it from planet.osm.org and those planets are encoded by a different piece of software. If we re-encode it using osmium and it becomes slower to read then, it could have something to do with that encoding.

**Comment by mmd-osm** [comment]
If you happen to have linux perf-tools installed, you can run "perf record" and trace one run. Later check results using "perf report". It should be immediately visible where the time is spent.

**Comment by yanchenko-igor** [comment]
The result for copy is way slower then the original planet file:
```
[ 0:00] Copying input file 'planet-copy.osm.pbf' (63932887701 bytes)
[======================================================================] 100% 
[35:51] Peak memory used: 169 MBytes
[35:51] Done.
```

**Comment by joto** [comment]
I have been able to reproduce this in so far as on my system reading the copy is slightly slower than reading the original planet. So the effect is there but much much smaller than on your system, I guess that's why it was never noticed.

So there must be something different between
a) those files which explains the difference
b) your server and mine which explains why the difference shows up so much larger in your case.

**Comment by yanchenko-igor** [comment]
Do you need any other info from me? my goal is to fix the performance issue that slows down it in general, i.e. on your server, the performance of my server is not very important, I am going to get another server for my project and it should be faster.

**Comment by joto** [comment]
@yanchenko-igor Thanks, not at the moment. I am a bit baffled and need to think about this and explore the differences between the files to get some ideas on would could be the problem. So for now I just need to find the time to research this further. I might come back to you when I have some theory or some code to test on your system.

To everybody else reading here: It might be useful to get timings from more and different systems, maybe we can find some commonalities/differences between systems which might account for the results.

**Comment by yanchenko-igor** [comment]
I am not sure if you noticed this, just wanted to point out, that reading the copy generated by osmium uses much less memory then the original planet file.

**Comment by joto** [comment]
Yeah, I noticed that. It happens on my system, too. But, again, the difference is much smaller than in your case. The memory is probably used for buffers and for some reason there is a difference there.

**Comment by mmd-osm** [comment]
It would be also interesting to compare the full output of `/usr/bin/time -v …` for both runs.

**Comment by yanchenko-igor** [comment]
```
# /usr/bin/time -v osmium cat -v /data/planet-latest.osm.pbf -f blackhole
[ 0:00] Started osmium cat
[ 0:00]   osmium version 1.13.1 (v1.13.1-13-gb5c4fc3)
[ 0:00]   libosmium version 2.17.0
[ 0:00] Command line options and default settings:
[ 0:00]   input options:
[ 0:00]     file names: 
[ 0:00]       /data/planet-latest.osm.pbf
[ 0:00]     file format: 
[ 0:00]   output options:
[ 0:00]     file name: 
[ 0:00]     file format: blackhole
[ 0:00]     generator: osmium/1.13.1
[ 0:00]     overwrite: no
[ 0:00]     fsync: no
[ 0:00]   other options:
[ 0:00]     object types: node way relation changeset
[ 0:00]     attributes to clean: (none)
[ 0:00] Copying input file '/data/planet-latest.osm.pbf' (61529736112 bytes)
[======================================================================] 100% 
[ 7:36] Peak memory used: 1261 MBytes
[ 7:36] Done.
        Command being timed: "osmium cat -v /data/planet-latest.osm.pbf -f blackhole"
        User time (seconds): 2651.07
        System time (seconds): 643.89
        Percent of CPU this job got: 723%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 7m 35.69s
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 4841344
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 19
        Minor (reclaiming a frame) page faults: 97696943
        Voluntary context switches: 1473054
        Involuntary context switches: 290561
        Swaps: 0
        File system inputs: 120177944
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```
```
# /usr/bin/time -v osmium cat -v planet-copy.osm.pbf  -f blackhole
[ 0:00] Started osmium cat
[ 0:00]   osmium version 1.13.1 (v1.13.1-13-gb5c4fc3)
[ 0:00]   libosmium version 2.17.0
[ 0:00] Command line options and default settings:
[ 0:00]   input options:
[ 0:00]     file names: 
[ 0:00]       planet-copy.osm.pbf
[ 0:00]     file format: 
[ 0:00]   output options:
[ 0:00]     file name: 
[ 0:00]     file format: blackhole
[ 0:00]     generator: osmium/1.13.1
[ 0:00]     overwrite: no
[ 0:00]     fsync: no
[ 0:00]   other options:
[ 0:00]     object types: node way relation changeset
[ 0:00]     attributes to clean: (none)
[ 0:00] Copying input file 'planet-copy.osm.pbf' (63932887701 bytes)
[======================================================================] 100% 
[32:29] Peak memory used: 216 MBytes
[32:29] Done.
        Command being timed: "osmium cat -v planet-copy.osm.pbf -f blackhole"
        User time (seconds): 2574.18
        System time (seconds): 2383.67
        Percent of CPU this job got: 254%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 32m 28.53s
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 826976
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 596875448
        Voluntary context switches: 16120137
        Involuntary context switches: 1127892
        Swaps: 0
        File system inputs: 45962552
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by mmd-osm** [comment]
Thanks, I think this is quite interesting. User time is very similar in both cases. However, for some reason, planet-copy has a much higher system time, and the percent of CPU this job got is much lower (723% vs. 254%). Effectively, planet-copy runs only on 1/3 of the CPU resources compared to the planet-latest run.

My first guess at the moment is that there seems to be some kind of lock contention or threading issue.

**Comment by joto** [comment]
Okay, I found the difference between the planet generated by planet-dump-ng and osmium. Osmium uses a much smaller block size for the internal blocks, so there are 2-3 orders of magnitude more blocks. It is to be expected that more blocks have a larger overhead then fewer blocks. But I don't know why that overhead is that large. You can test this by removing [these lines](https://github.com/osmcode/libosmium/blob/master/include/osmium/io/detail/pbf_output_format.hpp#L370-L372) from libosmium and recompiling osmium-tool, then re-generating the planet copy and then reading that one. So while the problem appears on the reading side, it is the writing side of osmium that is the actual problem.

I need to do more tests and benchmarks to see how to best tune this, so the "official" fix will need some time.

**Comment by yanchenko-igor** [comment]
I tried to rebuild the app with removed lines, then I tried to extract europe from planet file, it worked, but when I try to extract munich from europe file, I get an error after few seconds: 
```
$ osmium extract -b 11.35,48.05,11.73,48.25 /srv/gis/pbf/europe.osm.pbf --overwrite  -o munich_from_europe.osm.pbf
[======================================================================] 100% 
PBF error: illegal blob size
```
the same happens when I run `osmium cat -v  planet-copy.osm.pbf -f blackhole` on the newly created planet copy file.

**Comment by joto** [comment]
I did some changes to the PBF reading code in libosmium which seem to improve the situation in my tests. @yanchenko-igor Can you recompile with libosmium master and run the `osmium cat -f blackhole` tests again?

**Comment by yanchenko-igor** [comment]
The results with the latest osmium:
```
# osmium cat -v planet-copy.osm.pbf    -f blackhole
[ 0:00] Started osmium cat
[ 0:00]   osmium version 1.13.1 (v1.13.1-13-gb5c4fc3)
[ 0:00]   libosmium version 2.17.0
[ 0:00] Command line options and default settings:
[ 0:00]   input options:
[ 0:00]     file names: 
[ 0:00]       planet-copy.osm.pbf
[ 0:00]     file format: 
[ 0:00]   output options:
[ 0:00]     file name: 
[ 0:00]     file format: blackhole
[ 0:00]     generator: osmium/1.13.1
[ 0:00]     overwrite: no
[ 0:00]     fsync: no
[ 0:00]   other options:
[ 0:00]     object types: node way relation changeset
[ 0:00]     attributes to clean: (none)
[ 0:00] Copying input file 'planet-copy.osm.pbf' (64864112374 bytes)
[======================================================================] 100% 
[20:12] Peak memory used: 216 MBytes
[20:12] Done.
```

```
# osmium cat -v planet-latest.osm.pbf   -f blackhole
[ 0:00] Started osmium cat
[ 0:00]   osmium version 1.13.1 (v1.13.1-13-gb5c4fc3)
[ 0:00]   libosmium version 2.17.0
[ 0:00] Command line options and default settings:
[ 0:00]   input options:
[ 0:00]     file names: 
[ 0:00]       /data/igor_test/tmp/planet-latest.osm.pbf
[ 0:00]     file format: 
[ 0:00]   output options:
[ 0:00]     file name: 
[ 0:00]     file format: blackhole
[ 0:00]     generator: osmium/1.13.1
[ 0:00]     overwrite: no
[ 0:00]     fsync: no
[ 0:00]   other options:
[ 0:00]     object types: node way relation changeset
[ 0:00]     attributes to clean: (none)
[ 0:00] Copying input file 'planet-latest.osm.pbf' (62412473470 bytes)
[======================================================================] 100% 
[ 8:29] Peak memory used: 1192 MBytes
[ 8:29] Done.
```

**Comment by joto** [comment]
@yanchenko-igor Can you try the `osmium cat -f blackhole` with the changes in [this libosmium PR](https://github.com/osmcode/libosmium/pull/334)?

Hopefully with those changes the differences between `planet-latest` and `planet-copy` should be smaller and both should be faster.

**Comment by yanchenko-igor** [comment]
Sorry for the delay, I didn't have access to test the changes in the same environment, new tests show the following results: planet - 22 minutes, europe - 5 minutes, germany - 45 seconds, so the issue is fixed.
