### ISSUE TITLE
Missing Bounding Boxes after apply-changes

### ISSUE THREAD

**Issue by dooley** [osmcode/osmium-tool#219]
I loose the bounding boxes in the header  after

> osmium apply-changes $PBF_FILE $CHANGESET_FILE --no-progress --overwrite --output $PBF_TEMP \
>   --output-header=osmosis_replication_sequence_number=${sequenceNumber} \
>   --output-header=osmosis_replication_timestamp=${timestamp} \
>   --output-header=osmosis_replication_base_url=${REPLICATION_BASE_URL}
> 

Do i miss something here? 

Downloaded file:

> File:
>   Name: dach-latest.osm.pbf
>   Format: PBF
>   Compression: none
>   Size: 4690819668
> Header:
>   Bounding boxes:
>     (5.864417,45.81617,17.16273,55.14777)
>   With history: no
>   Options:
>     generator=osmium/1.8.0
>     osmosis_replication_base_url=http://download.geofabrik.de/europe/dach-updates
>     osmosis_replication_sequence_number=2672
>     osmosis_replication_timestamp=2021-07-02T20:21:33Z
>     pbf_dense_nodes=true
>     timestamp=2021-07-02T20:21:33Z
> 

The changeset:

> File:
>   Name: 000_002_673.osc.gz
>   Format: XML
>   Compression: gzip
>   Size: 7608657
> Header:
>   Bounding boxes:
>   With history: yes
>   Options:
>     generator=osmium/1.8.0
>     version=0.6
> 

After osmium apply-changes:

> File:
>   Name: dach-latest.osm.pbf
>   Format: PBF
>   Compression: none
>   Size: 4691593437
> Header:
>   Bounding boxes:
>   With history: no
>   Options:
>     generator=osmium/1.11.1
>     osmosis_replication_base_url=http://download.geofabrik.de/europe/dach-updates
>     osmosis_replication_sequence_number=2673
>     osmosis_replication_timestamp=2021-07-03T20:21:43Z
>     pbf_dense_nodes=true
>     timestamp=2021-07-03T20:21:43Z
> 

Edit: 

> osmium --version
> osmium version 1.13.1 (v1.13.1-13-gb5c4fc3)
> libosmium version 2.17.0
> Supported PBF compression types: none zlib
> 
> Copyright (C) 2013-2021  Jochen Topf <jochen@topf.org>
> License: GNU GENERAL PUBLIC LICENSE Version 3 <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
>

**Comment by joto** [comment]
The bounding box in the header are always somewhat dodgy, it is unclear what they describe exactly. Do they mean "everything inside the bbox is in this file" or "nothing outside this bbox is in the file". What about incomplete relations? Osmium doesn't really know what the apply-changes actually changes, so to be on the safe side it doesn't set that header. Should it be set to the original one? What if there are some objects in the change file outside the bbox, should it grow? Should it shrink if the bbox becomes smaller? Reflecting the bbox accurately also means we will have to do more work, because the header is at the front of the file, but when we write that we don't know yet what's in the file.

Why do you need the bbox? What did you expect osmium to do?

**Comment by dooley** [comment]
I'm playing with [tilemaker](https://github.com/systemed/tilemaker). From the pbf with bbox supplied i got nice mbtiles, from the updated without bbox i got the error below (no other changes made).

I see the problems you described. Hm. Any chance to add a standalone-option like 

> osmium update-bbox xyz.osm.pbf

which could be run after apply-changes? 

> tilemaker --input ~/osm_data/dach-latest.osm.pbf --output /datengrab/tiles/dach_test.mbtiles --config resources/config-openmaptiles.json --process resources/process-openmaptiles.lua
> Layer place (z0-14)
> ...
> Layer landuse (z4-14)
> Layer urban_areas (z4-8) -> landuse
> Layer landcover (z0-14)
> Layer ice_shelf (z0-9) -> landcover
> Layer glacier (z2-9) -> landcover
> Layer mountain_peak (z11-14)
> Resizing osm store to size: 64M                
> Can't read shapefiles unless a bounding box is provided.
>

**Comment by dooley** [comment]
I solved my problem by running osmium extract after osmium apply-changes where i can set the bounds. No need for further action :-)

**Comment by keichan34** [comment]
I'm actually running in to this problem as well, and it would be nice if we could get support for the bounding box header in apply-changes. For example, even something like `--output-header=bbox!` would be a lot easier than having to do another `osmium extract` or pass the bounding box directly in to tilemaker via command line arguments (this is what I'm doing now).
