### ISSUE TITLE
[apply-changes] Dynamic numbering for "create" entries in OSC files.

### ISSUE THREAD

**Issue by atiannicelli** [osmcode/osmium-tool#224]
I'd like to alter the "apply-changes" function to dynamically assign IDs for "create" entries in applied OSC files.

The issue that I have is that I have two OSC files that have thousands of entries in each one. Some are "modify" entries (so the IDs matter and must match the IDs in the PBF that I'm applying the OSC file) and then some are "create" entries (So the ID values for these entries don't matter, but better not overlap with the pbf that the osc is being applied to). Each of the two files start ID numbering for the first "create" entry at whatever the max ID in the pbf + 1. This means that I can apply either ONE of the two OCS files to the pbf, but if I want to apply BOTH I am unable because both OSC files contain the same IDs for many of the "create" entries. 

I was going to use the "renumber" function to renumber the "second" OSC file that I apply so that the create IDs start where the first OSC file ends, but the issue there is that the renumber function will also renumber the "modify" entries in the OSC file making all the "modify" entries bogus because they no longer match with the original pbf.

So I wanted to add a --dynamic flag to the "apply-changes" function so that it would basically do the following:
1) find the largest ID in the PBF for each feature type. Or if the user specifies starting IDs just start with those.
2) create a mapping table to keep track of the mapping from the OSC ID to new dynamic ID.
3) Start New Dynamic IDs at <pbf max ID per feature> + 1
4) Do normal application of the OSC files but set the IDs for created features according to the mapping table.

The rules for the OSC files would be:
1) All "create" IDs are unique within this specific OSC and are only referenced from other entries within the OSC.
2) Multiple OSCs can use the same ID for different create entries since the create IDs are specific to each OSC.
3) Mulitple OSC file can not reference IDs that are created within another OSC that is being applied when --dynamic parameter is specified.
4) All "modify" IDs must match the pbf's IDs as they must today.

I haven't looked at the apply-changes code yet so I'm assuming that it is possible to do, but I'm not sure yet how hard it will be. I first wanted to know if it would be acceptable to add this functionality.

**Comment by joto** [comment]
Osmium is first and foremost a tool to work with *OSM* data and *OSM* workflow. If you have data that's not OSM data but from some other source and Osmium works with it, great. But if it doesn't, there is only a limited amount of "bending backwards" that I am willing to do to support such use cases.

This sounds really like something you should solve outside of Osmium. Presumably you have some code that generates those change sets that you are applying. It should be the job of that code to generate unique IDs. You can use `osmium fileinfo` to get the largest IDs in your OSM file and feed that information into the code that generates these new IDs.

All that being said, there is an interesting similarity here with what JOSM does: JOSM internally uses negative IDs when generating new objects which are then "converted" to real IDs on upload. If you save an OSM file from JOSM, you can see those negative IDs. See also the [diff upload function of the API](https://wiki.openstreetmap.org/wiki/API_v0.6#Diff_upload:_POST_.2Fapi.2F0.6.2Fchangeset.2F.23id.2Fupload).

I could see that there might be some value in having a functionality compatible to that of JOSM. But I am not convinced, your use case actually needs that. Can you explain why you can't generate unique IDs in the first place, or use negative IDs? In any case, if we'd add something like this to Osmium, I would probably lean towards making this an extra command, not overload the meaning of `apply-changes`.

**Comment by atiannicelli** [comment]
Understood. Using negative IDs for created items is interesting, but I don't think it solves my issue (see below)

Here is an attempt to describe why we can't generate unique IDs in the first place:

Let's say I have a planet-osm-2021-07-29.pbf file that contains normal OSM data.
We can get the max Node ID (n), Way ID (w), and Relation ID (r) from that planet file, great.

But if we have to parallel teams working on two different types of changes (maybe two different locations, or two different feature types) Then we run in to this issue.

Team A, who is working on roads, generates an OSC file for thier work. It contains modified ways with IDs that match the planet-osm-2021-07-29.pbf, and it also has new ways and nodes that start at w+1 and n+1.
This team outputs: roads-2021-07-29.osc

Team B, who is working on buildings, generates an OSC file for thier work. It contains modified relations and ways with IDs that match the planet-osm-2021-07-29.pbf, and it also has new ways and nodes that start at w+1 and n+1.
This team outputs: buildings-2021-07-29.osc

Either of these OSC files will cleanly apply to the planet file if applied on their own. But, if I want to combine these two OSC files together with the planet-osm-2021-07-29.pbf my process must be something like this:
1) `osmium fileinfo -e roads-2021-07-29.osc` # to get the max IDs from one of the OSC files.
2) `osmium renumber -s n+1,w+1,r+1 buildings-2021-07-29.osc` # to start at the max IDs from step 1.
3) `osmium apply-changes --output new.pbf planet-osm-2021-07-29.pbf created-buildings-2021-07-29.osc modified-buildings-2021-07-29.osc roads-2021-07-29.osc`

But this won't work either because I don't want to renumber ALL of the entries in buildings-2021-07-29.osc, only the created ones. If I renumber all of the entries in buildings-2021-07-29.osc then the modify entries will be modifying features that don't exist. Maybe if there was a parameter to renumber that told renumber to only renumber "create" entries... I guess that would also fix my dilemma (If you like this better let me know). The only other way I know how to do it would be to serialize the two teams' OSC file generation so that one could not be created until the other had completed so the IDs could be coordinated.

You can also see that negative IDs doesn't solve this either because the two teams could generate newly created features with the same negative IDs and they would clash with each other unless one of the OSC files is renumbered.

**Comment by lonvia** [comment]
You might want to try hacking a Python script together with pyosmium that merges an renumbers all your osc files. Then you can use the resulting file with osmium apply-changes as is. This might be quicker than changing osmium-tool and you can adapt it to your exact needs. There is a [simple example](https://github.com/osmcode/pyosmium/blob/master/examples/normalize_boolean.py) how to read a file, change something and write it out again.

**Comment by joto** [comment]
You can also just use different ID ranges for you different teams. IDs don't have to be consecutive, so just assign non-overlapping ranges of new IDs to your teams. You have to take care that those ID ranges are not too large and too far outside of the normal OSM ID range, otherwise some processes might need a lot more memory, but that way you don't need to program anything really.

**Comment by atiannicelli** [comment]
Thanks! will do. thanks for the feedback.
