### ISSUE TITLE
Opposite of -r option?

### ISSUE THREAD

**Issue by rclark** [osmcode/osmium-tool#23]
The new `osmium getid --add-referenced` option lets you find all the dependencies of a single feature given its id. Would it be possible to run this in the opposite direction? Given an id (or list of ids), find all the features that it is a part of?

**Comment by joto** [comment]
I could imagine extending osmium to do this.

For the time being you can help yourself using OPL:

    egrep 'nXXX(,|$)' OSMFILE.osm.opl

will find all ways containing a node with id `XXX`. And

    grep wXXX@ OSMFILE.osm.opl

will find all relations with way member with id `XXX`. Same for (n)odes, and (r)elations. You can use multiple IDs by extending those regular expressions, but it will be a bit cumbersome.

**Comment by joto** [comment]
It is easy to get from nodes to the ways that contain them or from members to the relations that contain them. But is that enough? Do you then need all the other nodes in those ways, too, or all the members in those relations? This could lead to a very long recursive process: You start with a node on a road, find the way for that road, find all nodes in that way, find the ways from those nodes... You'll end up with the road network of a whole continent. And it will take forever.

@rclark What is your use case here? What do you expect it to do exactly?

**Comment by rclark** [comment]
I am experimenting with a coarse approach to splicing a planet into tiled pbfs. The idea would be:
- `osmium cat --object-type node --output-format opl` piped through a small JS script to find which tile each node belongs in and write it to the appropriate file. Now I have several files and the following steps can be run in parallel.
- 2nd pass on the planet to find the parent features of the nodes in one tiled output
- 3rd pass on the planet with existing `-r` option to fill in nodes outside the tile from ways that cross boundaries

That said, the general usage for this kind of "find the parents" functionality might tend to focus on single features, in which case the grep approach you outlined is perfect.

**Comment by joto** [comment]
That's basically what the history splitter does. Only slower. OPL is nice, but I don't think it is the right approach here.

**Comment by rclark** [comment]
... Sure there are faster approaches. I'm just trying to cobble together something that I can accomplish.

**Comment by joto** [comment]
Closing here. It is unclear how the semantics of this would look exactly.
