### ISSUE TITLE
extract memory usage now doubled on 1.13

### ISSUE THREAD

**Issue by pitney123456** [osmcode/osmium-tool#232]
Hello

I use the extract function to split country files from geofab continent files.
Using 1.10 I adjusted my json files so as to not exceed the 16gb of ram on my system.
Using 1.13 on the same continent files (as 1.10) my memory usage is apprx double.

I use complete ways, pbf_compression=none, add_metadata=false on both poly and bbox.
The only differences are upgrade to Debian 11 (from 10) and 1.13 from the Debian repository.
Any thoughts?

(please note that I cannot build sw)

thanks, pitney

**Comment by joto** [comment]
Can you be more specific? What command line exactly are you using, what config file, what input files?

**Comment by pitney123456** [comment]
Sorry, my bad.
With my previous runs I used strategy=simple which was deleted from my current script which then used strategy=complete_ways, doubling memory usage.
Adding strategy=simple back, all is good.
Thank you for continuing to develop Osmium.
pitney
