### ISSUE TITLE
"PBF error: invalid BlobHeader size (> max_blob_header_size)" when converting from TomTom Traffic API - Vector Flow Tiles PBF

### ISSUE THREAD

**Issue by chlorophyll-zz** [osmcode/osmium-tool#235]
## What version of osmium-tool are you using?

```
osmium --version
osmium version 1.13.2
libosmium version 2.17.0
Supported PBF compression types: none zlib lz4
```

## What operating system version are you using?

```
cat /etc/lsb-release 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2rc
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"
```

## Tell us something about your system
```
    description: Notebook
    product: 20A7002JUS (LENOVO_MT_20A7_BU_Think_FM_ThinkPad X1 Carbon 2nd)
    vendor: LENOVO
    version: ThinkPad X1 Carbon 2nd
```

4G RAM, 4x CPU, bare metal.

## What did you do exactly?

Input File:
https://developer.tomtom.com/content/traffic-api-explorer#/Traffic%20Flow/get_traffic_map__versionNumber__tile_flow__type___zoom___x___y___format_
Select "Traffic Flow" - "/traffic/map/{versionNumber}/tile/flow/{type}/{zoom}/{x}/{y}.{format}" - "Try it out"
```
osmium cat traffic.osm.pbf -f osm -o traffic.osm
PBF error: invalid BlobHeader size (> max_blob_header_size)

```
## What did you expect to happen?

Convert PBF file to OSM XML file

## What did happen instead?
`

```
osmium cat traffic.osm.pbf -o traffic.osm -f osm --verbose
[ 0:00] Started osmium cat
[ 0:00]   osmium version 1.13.2
[ 0:00]   libosmium version 2.17.0
[ 0:00] Command line options and default settings:
[ 0:00]   input options:
[ 0:00]     file names: 
[ 0:00]       traffic.osm.pbf
[ 0:00]     file format: 
[ 0:00]   output options:
[ 0:00]     file name: traffic.osm
[ 0:00]     file format: osm
[ 0:00]     generator: osmium/1.13.2
[ 0:00]     overwrite: no
[ 0:00]     fsync: no
[ 0:00]   other options:
[ 0:00]     object types: node way relation changeset
[ 0:00]     attributes to clean: (none)
PBF error: invalid BlobHeader size (> max_blob_header_size)

```
## What did you do to try analyzing the problem?

```
osmium fileinfo traffic.osm.pbf --verbose
[ 0:00] Started osmium fileinfo
[ 0:00]   osmium version 1.13.2
[ 0:00]   libosmium version 2.17.0
[ 0:00] Command line options and default settings:
[ 0:00]   input options:
[ 0:00]     file name: traffic.osm.pbf
[ 0:00]     file format: 
[ 0:00]   other options:
[ 0:00]     object types: node way relation changeset
[ 0:00]     extended output: no
[ 0:00]     calculate CRC: no
File:
  Name: traffic.osm.pbf
  Format: PBF
  Compression: none
  Size: 22824
PBF error: invalid BlobHeader size (> max_blob_header_size)

```

**Comment by joto** [comment]
Most likely the file is invalid. I suggest asking the TomTom support.

**Comment by joto** [comment]
I don't have any test data and no more information, so I assume this isn't Osmiums fault. Please open a new issue if you have a test case I can check that is failing where you are reasonably sure that this is a problem of Osmium.

**Comment by chlorophyll-zz** [comment]
@joto Here is a test data from TomTom Developers:
https://drive.google.com/file/d/1tgIxlBi6xE15nL9p4dNJJ5E4dTLYDkwm/view?usp=sharing

**Comment by joto** [comment]
Well, that doesn't work, because that's not an OSM PBF file but a Vector tile file. They confusingly sometimes use the same file file suffix, but they are totally different file formats.

**Comment by chlorophyll-zz** [comment]
Thank you.
