### ISSUE TITLE
merge-changes doesn't work as expected

### ISSUE THREAD

**Issue by TobWen** [osmcode/osmium-tool#24]
report for "osmium version 1.3.0" (https://github.com/osmcode/osmium-tool/commit/57715b178ef2482327b4e6c14f1928ed6cc4a8a5)

# Description of the issue
When merging multiple changefiles (gz-compressed osc) in combination with switch --simplify, the resulting changefile isn't merged correctly.

## Download changefiles
Sporadic (aprox. daily) changefiles from Geofabrik. This commands needs bash for increment, otherwise simply increment filename by 1 (144.osc.gz, 145.osc.gz etc.):
`wget http://download.geofabrik.de/europe-updates/000/001/14{2..6}.osc.gz `

## Do the merging and have a look at a way ID
```
osmium merge-changes *.osc.gz --simplify --output=test.osc
grep 414256828 -B1000 test.osc | grep -E 'delete|modify|create' | tail -n 1
```

### Issue
As you can see, the last action is `<create>`, but that's wrong. The last action should be `<delete>`. Way 414256828 got created in 144.osc.gz and got removed in 142.osc.gz - so it shouldn't appear in the final changefile.

### Different behaviour when dropping simplify
When dropping --simplify, the last action is correct. Of course, that's not what we want :)

## Digging deeper
I've figured out, that the bug only appears on wrong file order!

```
## 1.osc
<?xml version='1.0' encoding='UTF-8'?>
<osmChange version="0.6" generator="tobwen">
  <delete>
    <way id="414256828" version="1" timestamp="2016-05-03T00:18:16Z" uid="3497527" user="MCalascione" changeset="38966372">
      <nd ref="1177121444"/>
      <nd ref="4154263790"/>
      <nd ref="4154263890"/>
      <nd ref="4154253492"/>
      <nd ref="4137072356"/>
      <nd ref="1177121454"/>
      <tag k="highway" v="unclassified"/>
      <tag k="oneway" v="yes"/>
    </way>
  </delete>
</osmChange>
```
```
## 2.osc
<?xml version='1.0' encoding='UTF-8'?>
<osmChange version="0.6" generator="tobwen">
  <create>
    <way id="414256828" version="1" timestamp="2016-04-28T20:44:16Z" uid="3497527" user="MCalascione" changeset="38966372">
      <nd ref="1177121444"/>
      <nd ref="4154263790"/>
      <nd ref="4154263890"/>
      <nd ref="4154253492"/>
      <nd ref="4137072356"/>
      <nd ref="1177121454"/>
      <tag k="highway" v="unclassified"/>
      <tag k="oneway" v="yes"/>
    </way>
  </create>
</osmChange>
```

## Start a new test
* `osmium merge-changes 1.osc 2.osc --simplify --output=test_01.osc `
* `osmium merge-changes 2.osc 1.osc --simplify --output=test_02.osc`

Oops... First command gives the expected result, second doesn't. Seems like the order is important.

## Checking bash's expansion & Conclusion
When you expand *.osc.gz to full filenames, you can detect that the order is correct: `142.osc.gz 143.osc.gz 144.osc.gz 145.osc.gz 146.osc.gz`. So there might be an internal bug when using --simplify.

**Comment by TobWen** [comment]
The bug might have other reasons and not only osmium might be affected. I've written down my results in the German language in here: http://forum.openstreetmap.org/viewtopic.php?id=54521

**Comment by joto** [comment]
There are two different issues here:
* First, deleted objects should get a new ID, which they do in the planet diffs, but not in the Geofabrik diffs. I remember that this has already come up at some point, but don't remember the details.
* Second, the meaning of the `--simplify` option. When this option is set, Osmium simply removes all versions of an object except the last one. If there are two "versions" of an object having the same version number, the result is undefined, because this should never happen (but see first issue). In your case the object was created and then deleted, in which case we could just remove it completely from the result osc file. But what if we didn't see the creation, but a change and then the delete. We have to keep the delete in that case. It is more consistent to always keep the delete, which should not affect anybody applying this .osc file, but could help other who will see that there was an object there, although it is now deleted.

**Comment by TobWen** [comment]
To you first point: I think you mean "should a get a new **version**", don't you?
To your second point: Since I'm using changefile-extracts from Geofabrik, that might be the root of all evil? :)

**Comment by joto** [comment]
Geofabrik (and I would assume anybody else creating diffs from extracts) can create objects with different timestamps but same id and version. This is something I hadn't taken into account in libosmium. I have now updated libosmium to also order by timestamp, this should fix the issue with inconsistent ordering. To use this, you have to compile yourself using the newest libosmium master until new versions are released.

I am not convinced that  the OSM files (from Geofabrik) have the right format, but its what we have for the moment, so Osmium should now be able to handle this, although I haven't tested it properly.

I have updated the man page to clarify the behaviour of the `--simplify` option.

@TobWen I believe this should fix this issue for you. Can you test with master version of libosmium and osmium-tool?

**Comment by TobWen** [comment]
@joto Yeah, seems to work now. Good work.
