### ISSUE TITLE
file size change with apply-changes

### ISSUE THREAD

**Issue by dieterdreist** [osmcode/osmium-tool#247]
## What version of osmium-tool are you using?

osmium version 1.14.0
libosmium version 2.18.0
Supported PBF compression types: none zlib lz4

## What operating system version are you using?
macOS 12.3.1 (21E258)

## What did you do exactly?

osmium apply-changes planet-latest.osm.pbf ${CHANGES} -o ${PREFIX}-planet.osm.pbf

where changes is a string which lists 14 osc.gz files, totalling 1.1 GB

## What did you expect to happen?
moderate increase in file size

## What did happen instead?
planet grew from 63GB to 66GB

Maybe this is expected?

**Comment by joto** [comment]
The planet you can download on planet.osm.org is generated with a program that doesn't use libosmium. It encodes OSM data slightly different than how libosmium does it. Also we don't know what those changes are, they might well result in some objects moving into a different block inside the PBF or something like that making the whole file larger. So without looking at the details it is well possible that the file you get is somewhat larger than expected. I wouldn't consider this a bug.

**Comment by dieterdreist** [comment]
the diffs are the daily diffs from OpenStreetMap 2/5-today

**Comment by dieterdreist** [comment]
after continuing with the updates to the file I have found that the initial increase is now stable (not growing unexpectedly any more) which kind of confirms that the size differences are likely due to a different way of saving the pbf and not a problem.
