### ISSUE TITLE
man pages not installed with homebrew

### ISSUE THREAD

**Issue by dieterdreist** [osmcode/osmium-tool#249]
## What version of osmium-tool are you using?
osmium version 1.14.0
libosmium version 2.18.0
Supported PBF compression types: none zlib lz4

## What operating system version are you using?
macOS 12.4

Homebrew 3.5.2
Homebrew/homebrew-core (git revision e156c279eba; last commit 2022-06-28)
Homebrew/homebrew-cask (git revision 876edb5c28; last commit 2022-06-28)

## What did you do exactly?

install osmium-tool with
brew install osmium-tool

## What did you expect to happen?
man pages will be installed

## What did happen instead?
no link is created in 
/opt/homebrew/share/man/man1

and in
/opt/homebrew/Cellar/osmium-tool/1.14.0
there is no "share" subfolder where you would typically expect the man pages, there is only "bin"

## What did you do to try analyzing the problem?
not sure if here is the correct place to ask about this, otherwise excuse
This is not a new problem, the issue is there at least for several months

**Comment by joto** [comment]
You should ask the homebrew people about this. We don't have any say here about what and who homebrew does things.

**Comment by dieterdreist** [comment]
thank you, I'll try.
