### ISSUE TITLE
Run osmium on Windows

### ISSUE THREAD

**Issue by bmffb** [osmcode/osmium-tool#255]
## What version of osmium-tool are you using?
osmium version 1.14.0

## What operating system version are you using?
Windows 11, 64bit

## Tell us something about your system
laptop, i7, 16 GB RAM

## What did you do exactly?
I try to run a Python script (parse-routes.py) which is using osmium. The script is described [here](https://github.com/darauble/Locus-Map-DIY).

## What did you expect to happen?
That the script uses osmium to extract routes from a .pbf file.

## What did happen instead?
I get the error:
Traceback (most recent call last):
File "C:\Users\bernard\parse_routes.py", line 5, in
import osmium
ModuleNotFoundError: No module named 'osmium'

## What did you do to try analyzing the problem?
checked in the Anaconda Prompt if osmium is installed by `osmium --version` and got
   osmium version 1.14.0
   libosmium version 2.17.1
   Supported PBF compression types: none zlib lz4
   Copyright (C) 2013-2022 Jochen Topf [jochen@topf.org](mailto:jochen@topf.org)
   License: GNU GENERAL PUBLIC LICENSE Version 3 https://gnu.org/licenses/gpl.html.
   This is free software: you are free to change and redistribute it.
   There is NO WARRANTY, to the extent permitted by law.

For me it looks like that osmium is installed correctly. Still it can not be used in a Python script,
Any help is appreciated.

**Comment by ImreSamu** [comment]
crossposting: https://github.com/darauble/Locus-Map-DIY/issues/1

**Comment by joto** [comment]
Closing because this isn't related to osmium-tool.
