### ISSUE TITLE
osmium extract keeps some ways outside of the polygon

### ISSUE THREAD

**Issue by andrzejkurczewski-tomtom** [osmcode/osmium-tool#257]
## What version of osmium-tool are you using?

osmium version 1.14.0
libosmium version 2.17.3

## What operating system version are you using?

CentOS Linux 7

## What did you do exactly?

I downloaded the Planet PBF from https://planet.openstreetmap.org/
I used osmium to extract Croatia using `complete_ways` strategy:
```sh
osmium extract --strategy complete_ways -c extract_config.json input.pbf
```
where config is as follows:
```json
{
  "extracts": [
    {
      "output": "HRV.osm.pbf",
      "output_format": "pbf",
      "polygon": {
        "file_name": "HRV.geojson",
        "file_type": "geojson"
      }
    }
  ],
  "directory": "(...)"
}
```
Find geojson attached: [HRV.zip](https://github.com/osmcode/osmium-tool/files/10168917/HRV.zip)
It should be the same as country boundary in OSM, but it has a few months already.

## What did you expect to happen?

I expected an output file to contain ways and nodes located in or crossing the Croatia border.

## What did happen instead?

There are ways outside Croatia (located in Slovenia, Italy and Austria) included.
Below you can find the resulting PBF filtered with `osmfilter` for `highway=path` only, for easier visualization:
[complete_paths.zip](https://github.com/osmcode/osmium-tool/files/10168972/complete_paths.zip)
And the visualization:
![unexpected_paths](https://user-images.githubusercontent.com/84323323/205985131-dcd729de-601c-4081-809f-5df69f5d2bbd.png)

Sorry for such large-scale example. I failed to reproduce this issue when extracting smaller areas.
However, it did reproduce for multiple country polygons, including Austria, Czechia, Greece, Hungary or Italy.

In all cases the unexpected ways seem to cross the north edge of the country bounding box.

**Comment by dieterdreist** [comment]
maybe they are part of a long distance relation that crosses your borders?

**Comment by joto** [comment]
I can reproduce the problem, so there is definitely a bug there. Looks to me like some rounding problem at the bounding box edges or so. This needs some investigation.

**Comment by andrzejkurczewski-tomtom** [comment]
Maybe one more useful remark - it seems the problem doesn't occur with `simple` strategy.

**Comment by joto** [comment]
@andrzejkurczewski-tomtom Are you sure? When I tested it, it happened with the `simple` strategy, too.

**Comment by andrzejkurczewski-tomtom** [comment]
Croatia (exactly the same geojson) was the only country I checked with `simple`:
```sh
osmium extract --strategy simple -c extract_config.json input.pbf
```
And that was my result:
![image](https://user-images.githubusercontent.com/84323323/206323031-b7cc0c34-8c18-4354-91db-634ce8f04a21.png)
[simple_paths.zip](https://github.com/osmcode/osmium-tool/files/10180914/simple_paths.zip)

**Comment by joto** [comment]
I believe this is fixed in the current master. Can you check whether it works for you?

**Comment by joto** [comment]
No feedback, so assuming this has been fixed.

**Comment by andrzejkurczewski-tomtom** [comment]
Hi @joto, sorry for the late response.
I can confirm it works for me with 1.15 release, thanks a lot!
