### ISSUE TITLE
`delete` uses past instead of future version in OsmChange file

### ISSUE THREAD

**Issue by clarisma** [osmcode/osmium-tool#261]
`<osmChange version="0.6" generator="osmium/1.14.0">`

- The `delete` actions in an OsmChange file generated by Osmium contain the *past* (pre-change) version and timestamp of an element.
- `create` and `modify` contain the *future* (post-change) version and timestamp.
- The [OsmChange wiki page](https://wiki.openstreetmap.org/wiki/OsmChange) does not specify the behavior.
- However, `osmdbt-create-diff/0.6` (which creates the planet diffs) uses *future* (post-change) version/timestamp for all three actions.
- Osmium's approach makes it harder to determine the latest change if there are multiple `modify` actions for the same element, followed by a `delete`; therefore, I think it should match the behavior of `osmdbt-create-diff`.

**Comment by joto** [comment]
Can you give an example of the command line you are using and the input files?

**Comment by clarisma** [comment]
I didn't run this myself, I noticed this in files downloaded from Geofabrik: http://download.geofabrik.de/europe/france/provence-alpes-cote-d-azur-updates/

**Comment by clarisma** [comment]
I think I know what's going on: For extracts, Geofabrik creates diffs between the latest PBF and the one from the previous day, so Osmium doesn't have any information about the timestamp of the deletion (which is only stored on the OSM server or in history files) -- it only knows that a particular element from the previous PBF is not contained in the current PBF. 
Still, would it make more sense to increment the version number and use the timestamp of the latest PBF as the `delete` timestamp?
