### ISSUE TITLE
Merged .poly files with overlapping regions leave empty island

### ISSUE THREAD

**Issue by tordans** [osmcode/osmium-tool#266]
We have a folder of `.poly` files ([Folder](https://github.com/FixMyBerlin/atlas-geo/tree/develop/app/filter/regions)) that we `cat`-merge ([Github Code](https://github.com/FixMyBerlin/atlas-geo/blob/develop/app/run-2-filter.sh#L28-L34)) and use via `osmium extract --overwrite --polygon=${MERGED_POLY_FILE} --output=${OSM_REGIONS} ${OSM_GERMANY}`

Some of those shapes overlap.

We expected those overlaps to be part of our processed data. However, it looks like the overlap leaves empty islands of data.

|[Shape1](https://github.com/FixMyBerlin/atlas-geo/blob/develop/app/filter/regions/geojson/berlin-ring.geojson)|[Shape2](https://github.com/FixMyBerlin/atlas-geo/blob/develop/app/filter/regions/geojson/eichwalde.geojson)|[Result](https://radverkehrsatlas.de/regionen/berlin?lat=52.4716&lng=13.4463&zoom=14.6&theme=bikelanes&bg=default&config=!(i~fromTo~topics~!(i~shops~a~_F~s~!(i~default~a))(i~education~a~_F~s~!(i~default~a))(i~places~a~_F~s~!(i~default~a)(i~circle~a~_F))(i~buildings~a~_F~s~!(i~default~a))(i~landuse~a~~s~!(i~default~a))(i~barriers~a~_F~s~!(i~default~a))(i~boundaries~a~_F~s~!(i~default~a~~f~!(i~admin*_level~o~!(i~*7~a~_F)(i~*8~a)))))(i~bikelanes~topics~!(i~bikelanes~a~~s~!(i~default~a)(i~verification~a~_F)(i~completeness~a~_F))(i~bikelanesPresence~a~~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~circle~a~_F))(i~landuse~a~~s~!(i~default~a)))(i~roadClassification~topics~!(i~roadClassification~a~~s~!(i~default~a))(i~bikelanes~a~~s~!(i~default~a)(i~verification~a~_F)(i~completeness~a~_F))(i~maxspeed~a~~s~!(i~default~a)(i~details~a~_F))(i~surfaceQuality~a~~s~!(i~default~a)(i~bad~a~_F)(i~completeness~a~_F)(i~freshness~a~_F))(i~places~a~~s~!(i~default~a)(i~circle~a~_F))(i~landuse~a~~s~!(i~default~a)))(i~parking~topics~!(i~parking~a~~s~!(i~default~a)(i~presence~a~_F)(i~surface~a~_F))(i~parkingPoints~a~_F~s~!(i~default~a))(i~parkingAreas~a~~s~!(i~default~a)(i~position-separate~a~_F))(i~parkingDebug~a~_F~s~!(i~default~a))(i~parkingStats~a~_F~s~!(i~default~a~~f~!(i~admin*_level~o~!(i~*4~a~_F)(i~*9~a)(i~*10~a~_F)))(i~length~a~_F~f~!(i~admin*_level~o~!(i~*4~a~_F)(i~*9~a)(i~*10~a~_F))))(i~landuse~a~_F~s~!(i~default~a)))(i~lit~topics~!(i~lit~a~~s~!(i~default~a)(i~completeness~a~_F)(i~verification~a~_F)(i~freshness~a~_F))(i~places~a~_F~s~!(i~default~a)(i~circle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))~&mapDebug=true)|
|---|---|---|
|![shape1](https://user-images.githubusercontent.com/111561/233397621-ea5edd4f-dc12-400a-b49f-da5b1bef6d7f.png)|![shape2](https://user-images.githubusercontent.com/111561/233397620-eb4d1a88-4967-46d7-8bbc-664ef34611da.png)|![result](https://user-images.githubusercontent.com/111561/233397612-0c087c72-8d89-4324-9e8e-05d38ef36d38.png)|

I am wondering…
* Is this a bug or a feature? (I did not find any hints on this [in the docs](https://docs.osmcode.org/osmium/latest/osmium-extract.html).)
* Is there an quick way to fix this using `.poly`-files?

Otherwise, it is no problem to change our pre-processing to first merge the areas and pass a merged file to `osmium extract`.

**Comment by joto** [comment]
The docs explicitly mentions this case: "If there are several (multi)polygons in a poly file or OSM file, they will be merged. The (multi)polygons must not overlap, otherwise the result is undefined." So you have to merge those polygons some way first.

**Comment by tordans** [comment]
Thanks @joto 

> So you have to merge those polygons some way first.

I worked around this for now with a custom node script that merges our gejsons first (https://github.com/FixMyBerlin/atlas-geo/commit/c8851beb4de1f8f125125f0023cd2471d2b426e6#diff-315f020a80b5e8cab732efede00d88a605d192eda912886c4ac4c9700f22f471). We will refactor this along the way, but maybe its useful for someone reading this…

> The docs explicitly mentions this case: "If there are several (multi)polygons in a poly file or OSM file, they will be merged. The (multi)polygons must not overlap, otherwise the result is undefined." 

I wanted to create a PR to change the wording to more explicitly state what "undefined" means in this case. When I was first debugging this, "undefined" did not signal "will not be processed" or "will leave this space empty". — Can you point me to where those docs are hosted, [I did not find them](https://github.com/search?q=org%3Aosmcode+%22result+is+undefined%22&type=code)…

**Comment by joto** [comment]
The docs are in the repo: https://github.com/osmcode /osmium-tool/blob/master/man/osmium-extract.md

"undefined" is maybe not the best word here. For a C++ developer "undefined" has a very well defined meaning, it basically means "we are not promising anything if you do this". But not everybody is a C++ developer. :-)
