### ISSUE TITLE
osmium-extract geofabric osm data with bbox returns empty file

### ISSUE THREAD

**Issue by Afler** [osmcode/osmium-tool#272]
## What version of osmium-tool are you using?
osmium version 1.16.0
libosmium version 2.17.1

## What operating system version are you using?
Windows 10

## Tell us something about your system
6 CPU's
16GB RAM

## What did you do exactly?
osmium extract -b 57.23477323002487,35.95095020022178,54.35791022663538,39.6298223870818 --fsync -O -v -o "G:\osm\test.osm" "G:\osm\central-fed-district-latest.osm.pbf"

## What did you expect to happen?
I've wanted to get test.osm file with clipped osm data according to bbox

## What did happen instead?
test.osm contains only this:

```
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmium/1.16.0">
</osm>
```

## What did you do to try analyzing the problem?
I've tried to change bbox coords, do same processing with cofn.json file, got nothing

The osm file I used you can find here: https://download.geofabrik.de/russia/central-fed-district.html

**Comment by ImreSamu** [comment]
Hi @Afler 

I believe the order of the bbox parameters in your example is incorrect. The following command worked for me:

```
osmium extract -b 35.951,54.358,39.630,57.235  --fsync -O -v -o test.osm.pbf central-fed-district-latest.osm.pbf

# test:
osmium fileinfo -e test.osm.pbf 

File:
  Name: test.osm.pbf
  Format: PBF
  Compression: none
  Size: 259080002
Header:
  Bounding boxes:
  With history: no
  Options:
    generator=osmium/1.14.0
    pbf_dense_nodes=true
    pbf_optional_feature_0=Sort.Type_then_ID
    sorting=Type_then_ID
[======================================================================] 100% 
Data:
  Bounding box: (30.4599097,51.6539935,41.1666697,59.8445997)
  Timestamps:
    First: 2007-07-08T13:32:05Z
    Last: 2023-10-19T19:35:22Z
  Objects ordered (by type and id): yes
  Multiple versions of same object: no
  CRC32: not calculated (use --crc/-c to enable)
  Number of changesets: 0
  Number of nodes: 26769695
  Number of ways: 4059168
  Number of relations: 175389
  Smallest changeset ID: 0
  Smallest node ID: 1000
  Smallest way ID: 4480171
  Smallest relation ID: 14530
  Largest changeset ID: 0
  Largest node ID: 11275789927
  Largest way ID: 1216898612
  Largest relation ID: 16527212
  Number of buffers: 40776 (avg 760 objects per buffer)
  Sum of buffer sizes: 2538911960 (2.421 GB)
  Sum of buffer capacities: 2681274368 (2.557 GB, 95% full)
Metadata:
  All objects have following metadata attributes: version+timestamp
  Some objects have following metadata attributes: version+timestamp

```

**Comment by Afler** [comment]
@ImreSamu I see, my mistake. Thank you!
