### ISSUE TITLE
Sorting opl from stdin doesn't work

### ISSUE THREAD

**Issue by zdila** [osmcode/osmium-tool#278]
## What version of osmium-tool are you using?

osmium version 1.16.0
libosmium version 2.20.0
Supported PBF compression types: none zlib lz4

## What operating system version are you using?

Linux bono 6.11.2-amd64 # 1 SMP PREEMPT_DYNAMIC Debian 6.11.2-1 (2024-10-05) x86_64 GNU/Linux

## What did you do exactly?

`cat input.opl | osmium sort -F opl -f opl`

## What did you expect to happen?

To sort OPL from stdin and print it to stdout

## What did happen instead?

Nothing is printed to stdout.

**Comment by joto** [comment]
This should be fixed now in master.
