### ISSUE TITLE
Error message Osmium buffer is full using derive-changes

### ISSUE THREAD

**Issue by flymarq** [osmcode/osmium-tool#279]
## What version of osmium-tool are you using?

```
osmium --version
osmium version 1.16.0
libosmium version 2.20.0
Supported PBF compression types: none zlib lz4

Copyright (C) 2013-2023  Jochen Topf <jochen@topf.org>
License: GNU GENERAL PUBLIC LICENSE Version 3 <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
## What operating system version are you using?

Debian bookworm
```
cat /etc/debian_version 
12.8
```

## Tell us something about your system

 - bare metal
 - 32GB RAM
 - 1 CPU, 4 cores

## What did you do exactly?

```
/usr/bin/osmium derive-changes --no-progress --output CL.osc.bz2 CL-202410240100.osm.pbf CL-202411011400.osm.pbf
Osmium buffer is full
```

The osm.pbf-files are too big to be attached but can be downloaded here
- osm-file1: https://osm.download.movisda.io/admin/CL-202410240100.osm.pbf
- osm-file2: https://osm.download.movisda.io/admin/CL-202411011400.osm.pbf

## What did you expect to happen?

The job should finish without any message and return code zero. This issue was found producing more than 3000 changeset for different regions.

## What did happen instead?

The job finishes with none null return code and the error message `Osmium buffer is full`. The osc.bz2 ist generated but incomplete, at least the footer/closing xml-tag is missing.

## What did you do to try analyzing the problem?

Looking into the code os osmium-tool and libosmium this seems to be an issue in the memory management. I did not find any option or environment variable to change the memory settings.

**Comment by joto** [comment]
There is a way in your data with over a million nodes. 2000 nodes is the limit. Fix your data.

**Comment by joto** [comment]
https://wiki.openstreetmap.org/wiki/Way
