### ISSUE TITLE
`osmium-extract` doesn't include all the relations correctly due to a bug in `libosmium` library.

### ISSUE THREAD

**Issue by alexeisolodovnicov-tomtom** [osmcode/osmium-tool#281]
## What version of osmium-tool are you using?

Latest version

## What did you do exactly?

I found the issue while running osmium-extract command. My data had 3 relations: 2 relation with nodes members, and one "super-relation" (ID r4350609883), which has the previous two relations as members.

## What did you expect to happen?

I expected to have all the three relations after the `osmium-extract` command.

## What did happen instead?

My "super-relation" was not in the output data after `osmium-extract` command.

## What did you do to try analyzing the problem?

The problem was caused by the osmium-tool. It uses `libosmium` for the `osmium-extract` command, e.g. in the code for `osmium-extract` with SMART strategy [here](https://github.com/osmcode/osmium-tool/blob/master/src/extract/strategy_smart.cpp) it uses classes osmium::index::RelationsMapXXX from `libosmium`.
The RelationMapXXX classes have fields with maps, where the key and value type is uint32_t.
Specifically, [here for RelationsMapIndex](https://github.com/osmcode/libosmium/blob/master/include/osmium/index/relations_map.hpp#L174) and [here for RelationsMapStash](https://github.com/osmcode/libosmium/blob/master/include/osmium/index/relations_map.hpp#L315).

As we know, OSM IDs are 64bit. In case relation IDs are bigger than max uint32, the values silently overflow, and we have some "parent_id" values for relations which differ from actual relation IDs.

That is how I lost my "super-relation" with ID `4350609883`, which suddenly transformed into `55642587` (overflow: 4294967295-4350609883+1) for the parent relation.

**Comment by alexeisolodovnicov-tomtom** [comment]
The correspondent `libosmium` issue is [here](https://github.com/osmcode/libosmium/issues/381), the PR for the change is in place.

Although the NOTE for the bug issue claims:
```
If you are using non-OSM data with osmium and it fails, this is not considered a bug.
```

That looks like a generic problem, which could hit pretty much everyone in case a relation ID is higher than max uint (and still valid value).

The `osmium-getid` also uses that `libosmium` classes, which for sure can cause some strange behavior as well.

**Comment by joto** [comment]
No, it is not a generic problem. OSM data doesn't have IDs that big. This is specific to what TomTom does with these tools.

**Comment by joto** [comment]
Works fine for OSM data. Not a bug.

**Comment by salimbaidoun-tomtom** [comment]
@joto : what do you think will be the cost to conduct the bug fixing?
