### ISSUE TITLE
changeset-filter is not working

### ISSUE THREAD

**Issue by mapdevsaikat** [osmcode/osmium-tool#283]
## What version of osmium-tool are you using?

osmium version 1.16.0
libosmium version 2.20.0

## What operating system version are you using?

macOS Version 15.2 

## Tell us something about your system

Apple M1 Pro
Memory: 16 GB

## What did you do exactly?

I was trying to create a subset of the planet-osm-latest.osm.bz2 using the `changeset-filter`.
`osmium changeset-filter -a 2024-01-01T00:00:00Z -b 2024-01-31T23:59:59Z changesets-latest.osm.bz2 -o jan24-ch-filter.osm.bz2`

## What did you expect to happen?

It is supposed to generate a subset of changesets for January 2024 of the planate file.
Expected Output:  `jan24-ch-filter.osm.bz2` - Changesets of the January 2024.

## What did happen instead?

Not running or not throwing any error.  However, currently, I am trying this with the Geofabrik .osm.bz2 files (as the Planet OSM server is down)

**Comment by joto** [comment]
I don't believe Geofabrik offers changesets for download. So there might be a misunderstanding here. [Changesets](https://wiki.openstreetmap.org/wiki/Changeset) are something different that [change files](https://wiki.openstreetmap.org/wiki/OsmChange).

**Comment by mapdevsaikat** [comment]
Thank you, I was mistaken it was a file name confusion, I downloaded the wrong file. I got the changeset file, it is working fine. Thanks.
