### ISSUE TITLE
check-apply-changes-mixed{1,2} tests segfault on mips & mipsel

### ISSUE THREAD

**Issue by sebastic** [osmcode/osmium-tool#36]
The `check-apply-changes-mixed1` & `check-apply-changes-mixed2` caused the osmium-tool 1.4.0 builds on mips & mipsel to fail due to segfaults in these tests:

```
        Start  20: check-apply-changes-mixed1
 19/198 Test  #20: check-apply-changes-mixed1 ................***Exception: SegFault  0.10 sec

        Start  21: check-apply-changes-mixed2
 21/198 Test  #21: check-apply-changes-mixed2 ................***Exception: SegFault  0.10 sec
[...]
99% tests passed, 2 tests failed out of 198

Total Test time (real) =  29.51 sec

The following tests FAILED:
     20 - check-apply-changes-mixed1 (SEGFAULT)
     21 - check-apply-changes-mixed2 (SEGFAULT)
Errors while running CTest
```

Full buildlogs: [mips](https://buildd.debian.org/status/fetch.php?pkg=osmium-tool&arch=mips&ver=1.4.0-1&stamp=1473985894), [mipsel](https://buildd.debian.org/status/fetch.php?pkg=osmium-tool&arch=mipsel&ver=1.4.0-1&stamp=1473985550)

I've run the tests manually on the mips porterbox under gdb.

check-apply-changes-mixed1:

```
(gdb) run
Starting program: /home/sebastic/git/pkg-grass/osmium-tool-1.4.0/obj-mips-linux-gnu/src/osmium apply-changes test/apply-changes/input-data.osm test/apply-changes/input-change.osc -f osh
warning: GDB can't find the start of the function at 0x77fc6b8c.

    GDB is unable to find the start of the function at 0x77fc6b8c
and thus can't determine the size of that function's stack frame.
This means that GDB may be unable to access that stack frame, or
the frames below it.
    This problem is most likely caused by an invalid program counter or
stack pointer.
    However, if you think GDB should simply search farther back
from 0x77fc6b8c for code which looks like the beginning of a
function, you can increase the range of the search using the `set
heuristic-fence-post' command.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/mips-linux-gnu/libthread_db.so.1".
warning: GDB can't find the start of the function at 0x77fc7648.

Program received signal SIGSEGV, Segmentation fault.
0x5559bd80 in main (argc=6, argv=<optimized out>) at ./src/main.cpp:111
111             std::cerr << e.what() << std::endl;
(gdb) bt full
#0  0x5559bd80 in main (argc=6, argv=<optimized out>) at ./src/main.cpp:111
        e = @0x0: <incomplete type>
        command = "apply-changes"
        arguments = std::vector of length 4, capacity 8 = {"test/apply-changes/input-data.osm", "test/apply-changes/input-change.osc", "-f", "osh"}
        cmd = std::unique_ptr<Command> containing 0x556879a0
```

check-apply-changes-mixed2:

```
(gdb) run 
Starting program: /home/sebastic/git/pkg-grass/osmium-tool-1.4.0/obj-mips-linux-gnu/src/osmium apply-changes test/apply-changes/input-data.osh test/apply-changes/input-change.osc -f osm
warning: GDB can't find the start of the function at 0x77fc6b8c.

    GDB is unable to find the start of the function at 0x77fc6b8c
and thus can't determine the size of that function's stack frame.
This means that GDB may be unable to access that stack frame, or
the frames below it.
    This problem is most likely caused by an invalid program counter or
stack pointer.
    However, if you think GDB should simply search farther back
from 0x77fc6b8c for code which looks like the beginning of a
function, you can increase the range of the search using the `set
heuristic-fence-post' command.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/mips-linux-gnu/libthread_db.so.1".
warning: GDB can't find the start of the function at 0x77fc7648.

Program received signal SIGSEGV, Segmentation fault.
0x5559bd80 in main (argc=6, argv=<optimized out>) at ./src/main.cpp:111
111             std::cerr << e.what() << std::endl;
(gdb) bt full
#0  0x5559bd80 in main (argc=6, argv=<optimized out>) at ./src/main.cpp:111
        e = @0x0: <incomplete type>
        command = "apply-changes"
        arguments = std::vector of length 4, capacity 8 = {"test/apply-changes/input-data.osh", "test/apply-changes/input-change.osc", "-f", "osm"}
        cmd = std::unique_ptr<Command> containing 0x556879a0
```

**Comment by joto** [comment]
This is weird. Code works fine on other systems. Valgrind doesn't report any problems. And the code failing here isn't that complicated to begin with. It happens when catching an exception, but this test is supposed to throw and catch that exception, so that is alright.

Previous versions of this code have been around for a while, so it must have worked in earlier osmium-tool releases. The recent changes have been more cosmetic. If you want to, you could go back to earlier commits and try to figure out in which commit exactly the problem was introduced. I can't think of any other way to find this.

**Comment by sebastic** [comment]
It seems that for some reason `e.what()` is a NULL pointer.

The standard documents the following for `std::exception::what`:
> Pointer to a null-terminated string with explanatory information. The pointer is guaranteed to be valid at least until the exception object from which it is obtained is destroyed, or until a non-const member function on the exception object is called.

I guess the object from which the exception is obtained is destroyed before the exception is handled, this may be due to mips & mipsel being slower architectures where the exception is not handled fast enough as it is on the other architectures.

I've done some testing and calling `e.what()` after catching the exception triggers the segfault already, not allowing even to test for != NULL.

For now I'll ignore the test failures on mips & mipsel to allow the Debian package builds to succeed and enable the package to migrate to testing for inclusion in the next stable release and backporting to jessie-backports.

**Comment by joto** [comment]
Newer version of osmium-tool [seems to build fine](https://buildd.debian.org/status/logs.php?pkg=osmium-tool&ver=1.5.1-1) so this was most likely a problem with the system libraries or so. Closing here.

**Comment by sebastic** [comment]
That's because the test failures on mips & mipsel are ignored:
```make
override_dh_auto_test:
# Ignore test failures on problematic architectures only
ifneq (,$(findstring $(DEB_BUILD_ARCH),"mips mipsel"))
	dh_auto_test || echo "Ignoring test failures"
else
	dh_auto_test
endif
```
https://anonscm.debian.org/cgit/pkg-grass/osmium-tool.git/tree/debian/rules#n21

If you check the build logs (by clicking on the link in the Results column) and jump to the `dh_auto_test` section you'll see the tests still failing:
```
99% tests passed, 2 tests failed out of 198

Total Test time (real) =  34.01 sec

The following tests FAILED:
	 20 - check-apply-changes-mixed1 (SEGFAULT)
	 21 - check-apply-changes-mixed2 (SEGFAULT)
Errors while running CTest
```

**Comment by joto** [comment]
Ah, sorry. I'll re-open that, but still think it is not our fault.

**Comment by sebastic** [comment]
That's possible, there is a nasty binutils issue on mips* ([#844227](https://bugs.debian.org/844227)) which may be related.

I've ignored the test failures on mips* to not have the missing binaries on those archs be a blocker for testing migration.

**Comment by joto** [comment]
The current libosmium/osmium-tool code contains some build changes that will explicitly set the `-pthreads` option on the compiler which somebody needed. As this bug seems to be related to threading, maybe it helps here, too.

**Comment by sebastic** [comment]
Unfortunately the tests still failed on mips at least, the buidds haven't gotten around to building the packages on mipsel yet.

**Comment by sebastic** [comment]
The test failures are ignored on mips*, until actual users of the package on these architectures report the need to fix this issue, we can keep ignoring the failure.
