### ISSUE TITLE
Add referenced objects or not?

### ISSUE THREAD

**Issue by joto** [osmcode/osmium-tool#48]
There are several `osmium` commands that select some OSM objects from a file (`getid`, `extract`, `tags-filter` currently, probably more in the future). In many, but not all cases, the user not only want's the objects matching the selection criteria (an ID, tag, or so) but also the objects referenced by the matching objects. So the nodes for ways and the members for relations.

Currently the `getid` command and the `tags-filter` command have the `--add-referenced` option for that. the default is to only include matching objects. The `extract` command has its "strategies" here.

Often new users stumble about this and expect the default version of the command to "do the right thing" and include everything needed. But on the other hand this is a lot of extra work for the commands and a lot more data they generate, so having a default that is much more expensive seems wrong.

The other question is whether the current `--add-referenced` is enough. For the `extract` we already have a different way of specifying essentially the same issue, because there are more options that make sense. And I have already been thinking about adding an option to `getid` and `tags-filter` to add parent ways and/or relations.

**Comment by freenerd** [comment]
> Often new users stumble about this and expect the default version of the command to "do the right thing" and include everything needed. But on the other hand this is a lot of extra work for the commands and a lot more data they generate, so having a default that is much more expensive seems wrong.

To me, user error is more important to mitigate than avoiding extra CPU cycles.

**Comment by joto** [comment]
One solution would be to always require that the user sets a command line option. So they are forced to decide what they want. Slightly more cumbersome to use, but it tells the user: This is important, you have to think about this.

**Comment by joto** [comment]
`tags-filter` now adds referenced objects by default.
