### ISSUE TITLE
[OPL]  sorting tag keys for easy postprocessing

### ISSUE THREAD

**Issue by ImreSamu** [osmcode/osmium-tool#49]
Analyzing  `Sample_Thailand 03_14.osm` from ["Imports osm mail list"](https://lists.openstreetmap.org/pipermail/imports/2017-March/004840.html)  with `osmium` tool

I have got: 
```
osmium cat Sample_Thailand\ 03_14.osm -f opl |  grep "^w-" | cut -d" " -f8 | sort | uniq -c
[======================================================================] 100% 
      1 Tbridge=yes,highway=unclassified,import=yes,source=digitalglobe
      1 Thighway=primary,ref=109,source=sign,surface=paved
      1 Thighway=residential,import=yes,note=Connect%20%to%20%primary%20%highway%20%2/28/2017,source=digitalglobe
    206 Thighway=residential,import=yes,source=digitalglobe
      1 Thighway=residential,source=digitalglobe,import=yes
    263 Thighway=track,import=yes,source=digitalglobe
      3 Thighway=track,source=digitalglobe,import=yes
     74 Thighway=unclassified,import=yes,source=digitalglobe
      2 Thighway=unclassified,source=digitalglobe,import=yes
      2 Timport=yes,source=digitalglobe,highway=track
```

As I see, that same taggings has a different key orders  - so different lines,  And  my favorite `osmium cat` tricks ( ` sort | uniq -c ` )  not working here. So I see 2 summary lines,  but this is same taggings.
```
     74 Thighway=unclassified,import=yes,source=digitalglobe
      2 Thighway=unclassified,source=digitalglobe,import=yes
```

It is possible to add a keys sorted - OPL format  ( higway= ; import= ; source= ) ? 
So I will got only 1 lines for the same tag combinations.  ( 74 + 2 = 76 )
```
     76 Thighway=unclassified,import=yes,source=digitalglobe
```

I have tried alternative versions, without the expecting result :
* a.)
```
osmium cat Sample_Thailand\ 03_14.osm -f pbf > thai.osm.pbf
osmium cat thai.osm.pbf  -f opl | grep "^w-" | cut -d" " -f8 | sort | uniq -c
```
* b.)
`osmium sort Sample_Thailand\ 03_14.osm -f opl |  grep "^w-" | cut -d" " -f8 | sort | uniq -c`

tested with :  
```
 osmium --version
osmium version 1.6.0 (v1.6.0)
libosmium version 2.12.0
Copyright (C) 2013-2017  Jochen Topf <jochen@topf.org>
License: GNU GENERAL PUBLIC LICENSE Version 3 <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

test data: 
[Sample_Thailand 03_14.osm.zip](https://github.com/osmcode/osmium-tool/files/845895/Sample_Thailand.03_14.osm.zip)

I have checked the special options : http://docs.osmcode.org/osmium/latest/osmium-file-formats.html but I have not find any solutions.

**Comment by joto** [comment]
Osmium input and output never changes anything in the data. Sorting the tags would change the order of the tags (obviously), so I don't want to do this in the I/O "driver", the OPL output. This might be better in an extra command. But I am not sure about the usefulness. I think in OSM data, tags are normally sorted, so maybe you can ask the data source to order their tags. And even if you sort the tags, this solves only part of the problem, many different combinations of tags remain. Maybe this is something that is too much to be expected from the OPL format.

**Comment by ImreSamu** [comment]
> so I don't want to do this in the I/O "driver", the OPL output. 

ok,  

>This might be better in an extra command. .... I think in OSM data, tags are normally sorted, so maybe you can ask the data source to order their tags.

Maybe this is more likely an [osmium sort](http://docs.osmcode.org/osmium/latest/osmium-sort.html) related.

As I see  **now** the   `osmium sort` = _"Objects are sorted by type, ID, and version."_
So theoretically -  extending this  - with a  4th  sort variable ( `key` )  maybe help creating fully **"normally sorted"** osm data.  

It is not a critical or important , and no problem if it is not implemented.

**Comment by ImreSamu** [comment]
Side note:   

As I see , the   osm tag/key order - can be one of the very small differences between  `osmium diff` and `osmium derive-changes` algorithm.  ( I don't know it is worth to add to the documentation  or not , but it was a new information for me )
*  [osmium diff](http://docs.osmcode.org/osmium/latest/osmium-diff.html) _"Finds differences between two OSM files and displays them. ..."_
```
$ osmium diff t1_sorted.osm t2_sorted.osm -f opl
-n-1 v0 dV c0 t i0 u Tk1=v1,k2=v2 x99 y99
+n-1 v0 dV c0 t i0 u Tk2=v2,k1=v1 x99 y99
```

* [osmium derive-changes](http://docs.osmcode.org/osmium/latest/osmium-derive-changes.html).  _"Finds differences between two OSM files and creates a change file with those differences.  ... "_

```bash
$ osmium derive-changes t1_sorted.osm t2_sorted.osm -f osc
<?xml version='1.0' encoding='UTF-8'?>
<osmChange version="0.6" generator="osmium/1.6.0">
</osmChange>
```

full example: 
```bash
$ cat t1.osm
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="handmade">
  <node id="-1" lat="99" lon="99">
      <tag k="k1" v="v1"/>
      <tag k="k2" v="v2"/>
  </node>
</osm>
$ cat t2.osm
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="handmade">
  <node id="-1" lat="99" lon="99">
      <tag k="k2" v="v2"/>  
      <tag k="k1" v="v1"/>
  </node>
</osm>
$ osmium diff t1.osm t2.osm -f opl
-n-1 v0 dV c0 t i0 u Tk1=v1,k2=v2 x99 y99
+n-1 v0 dV c0 t i0 u Tk2=v2,k1=v1 x99 y99
$ osmium sort t1.osm -O -o t1_sorted.osm
$ osmium sort t2.osm -O -o t2_sorted.osm
$ osmium diff t1_sorted.osm t2_sorted.osm -f opl
-n-1 v0 dV c0 t i0 u Tk1=v1,k2=v2 x99 y99
+n-1 v0 dV c0 t i0 u Tk2=v2,k1=v1 x99 y99
$ osmium derive-changes t1_sorted.osm t2_sorted.osm -f osc
<?xml version='1.0' encoding='UTF-8'?>
<osmChange version="0.6" generator="osmium/1.6.0">
</osmChange>
```

**Comment by joto** [comment]
`derive-changes` only looks at the type, id, and version of the objects. It is there to create change files that can later be applied with `apply-changes`. In normal OSM data, the same object can't have different tag ordering, so that is not taken into acount.

`diff` on the other hand compares everything. It is for showing differences between files, for instance when comparing the output of two versions of some process to see whether they match.

I should probably make this distinction more clear in the manuals.

**Comment by joto** [comment]
I have updated the `derive-changes` and `diff` manpages as well as the [manual](http://osmcode.org/osmium-tool/manual.html#working-with-change-files).
