### ISSUE TITLE
Question about extracting a PBF history OSM file and header output

### ISSUE THREAD

**Issue by garaud** [osmcode/osmium-tool#51]
Hi,

I work on a planet full history PBF file and use `osmium extract` to select a smaller bounding box (France or a region of France). Then I use the `pyosmium` lib to extract some OSM features.

The launched command looks like:
`osmium extract --with-history --config=config.json --fsync history.osm.pbf` with a `config.json` such as:
```js
{
    "extracts": [
        {
            "output": "latest-region.pbf",
            "output_format": "pbf",
            "description": "extract OSM history for a smaller region",
            "bbox": {"left": -1.428,
                     "right": 1.813,
                     "top": 45.275,
                     "bottom": 42.940}
        }
    ],
    "directory": "/path/to/output-dir"
}
```
Unfortunately, when I look the header of the output file given by `osmium fileinfo`, I don't have a `with_history` set to `true` neither a defined bbox. I thought the `--output-header` could help me but the documentation said to read the libosmium manual and...well, I didn't find a mention to the list of allowed header options. I naively add a JSON field to my configuration file as:
```js
output_header: {
    "with_history": true
}
```
inside the first element of the `extracts` JSON list but without success.
How can I write a well header in my generated PBF file? The following problem is: when I parse the generated file with `pyosmium`, the `visible` attribute of each OSM entity is **always** set to `true`. So, three suppositions:

* the header value `with_history: no` shows that the PBF is not a history file, and then the optional `visible` attribute is set to its default value `true`
* Or if the generated PBF file doesn't have this specific information (i.e. `visible`)
* a third reason that I don't have known

Can you enlighten me about this `--output-header` option, the way to well-written the header and to have the real `visible` value of my history PBF file please? I feel that all this is related but maybe I'm wrong...

Best,
Damien

**Comment by joto** [comment]
This is, unfortunately, a bit of a mess. (Some of it my fault, some of it just missing specs from OSM.)

Give your history file(s) a suffix `osh.pbf` (instead of `osm.pbf` or just `pbf`) and you should be fine. Or use `"output_format": "osh.pbf"`. The [file formats manual](http://osmcode.org/file-formats-manual/) has some information about this. 

To add the bounding box to the header, use the `--set-bounds` option to `osmium extract`.

**Comment by garaud** [comment]
OK, I'll try that today. I didn't figure out it could be the output file format.

And about the `visible` attribute, do you know it's not present in the output PBF file generated by osmium extract? Or a reader, e.g. `pyosmium`, supposes that this attribute shouldn't be present because the `with_history` is set to no? I'm not sure to be very clear, sorry.

**Comment by joto** [comment]
When you do `osmium extract` with the `--with-history` option, the visible flag should work correctly.

**Comment by garaud** [comment]
I meant with an other reader such as `pyosmium`. I don't know how you can specify to the handler that this is a history PBF file.
As I have a well `with_history: yes` in the header of my generated osh.pbf file, I can close the issue.

Thank you for your time.
Damien
