### ISSUE TITLE
install not working

### ISSUE THREAD

**Issue by baditaflorin** [osmcode/osmium-tool#52]
mapuser@mapsrv:~/data/florinb/test/osmium-tool-1.6.0$ make
mkdir -p build && cd build && cmake .. && make
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:44 (find_package)

CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:44 (find_package)

CMake Error at cmake/FindOsmium.cmake:75 (file):
  file STRINGS file
  "/home/mapuser/data/florinb/test/osmium-tool-1.6.0/OSMIUM_INCLUDE_DIR-NOTFOUND/osmium/version.hpp"
  cannot be read.
Call Stack (most recent call first):
  CMakeLists.txt:47 (find_package)

-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for protozero
-- Looking for protozero - not found
CMake Warning at cmake/FindOsmium.cmake:143 (message):
  Osmium: Can not find some libraries for PBF input/output, please install
  them or configure the paths.
Call Stack (most recent call first):
  CMakeLists.txt:47 (find_package)

-- Could NOT find EXPAT (missing:  EXPAT_LIBRARY EXPAT_INCLUDE_DIR)
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
CMake Warning at cmake/FindOsmium.cmake:169 (message):
  Osmium: Can not find some libraries for XML input/output, please install
  them or configure the paths.
Call Stack (most recent call first):
  CMakeLists.txt:47 (find_package)

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Osmium: Found unsuitable version "unknown", but required is
  at least "2.12.0" (found OSMIUM_INCLUDE_DIR-NOTFOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOsmium.cmake:294 (find_package_handle_standard_args)
  CMakeLists.txt:47 (find_package)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/mapuser/data/florinb/test/osmium-tool-1.6.0
   used as include directory in directory /home/mapuser/data/florinb/test/osmium-tool-1.6.0

-- Configuring incomplete, errors occurred!
See also "/home/mapuser/data/florinb/test/osmium-tool-1.6.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/mapuser/data/florinb/test/osmium-tool-1.6.0/build/CMakeFiles/CMakeError.log".
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 1
mapuser@mapsrv:~/data/florinb/test/osmium-tool-1.6.0$

**Comment by joto** [comment]
You have to install all dependencies first, see README.

**Comment by asymmetric** [comment]
This seems to be a real issue. If on an Ubuntu 16.04 I follow the README and install `libosmium2-dev`, I get the above error.

If instead I install `libosmium-dev`, it works.

**Comment by joto** [comment]
@asymmetric Please read https://github.com/osmcode/osmium-tool/blob/master/CONTRIBUTING.md and try again.

**Comment by XiGuaSZ** [comment]
I have the same problem.I had install all dependencies,but also error :
"CMake Error at cmake/FindOsmium.cmake:75 (file):
file STRINGS file
"/home/mapuser/data/florinb/test/osmium-tool-1.6.0/OSMIUM_INCLUDE_DIR-NOTFOUND/osmium/version.hpp"

solution method:
in the same forld,
git clone https://github.com/osmcode/libosmium.git
git clone https://github.com/osmcode/osmium-tool.git
cd osmium-tool/
mkdir build 
cd  build
cmake ..
make 

that is ok.but i do not kown why.

**Comment by raxim1** [comment]
I have looked for this issue, as my latest ubuntu holds 1.3.1, i install with sudo apt-get install.

So i think libosmium is that old, when you would like to install from ubuntu centarl repository.
Latest version is 1.7.1 - so it seemed to be worth the upgrade.

protozero has not been found among ubuntu packages. (16.4.3 -xenial)

I think the docs needs to be uptodate.

To XiGuaSZ i would have spent hours to figure out why things are not working, which is a shame.
Thanks for the info.
Joto: you have closed a real programmatic issue at the beginning, instead of investigating this very basic manner.

**Comment by ktjaco** [comment]
@raxim1 @XiGuaSZ @asymmetric My builds were successful but the command was still not found. I fixed this by simply copying the **```osmium```** file to ```/usr/bin```.

**Comment by gplv2** [comment]
> protozero has not been found among ubuntu packages. (16.4.3 -xenial)

The readme is indeed a bit unclear, the name of the package is libprotozero-dev for ubuntu 16.04

I can confirm that if you follow the current readme, you won't be able to build and will end up on this page after googling / duckduckgo.com
