### ISSUE TITLE
install not working

### ISSUE THREAD

**Issue by baditaflorin** [osmcode/osmium-tool#53]
mapuser@mapsrv:~/data/florinb/test/osmium-tool-1.6.0/build$ cmake ..
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
CMake Error at cmake/FindOsmium.cmake:75 (file):
  file STRINGS file
  "/home/mapuser/data/florinb/test/osmium-tool-1.6.0/OSMIUM_INCLUDE_DIR-NOTFOUND/osmium/version.hpp"
  cannot be read.
Call Stack (most recent call first):
  CMakeLists.txt:47 (find_package)

-- Looking for protozero
-- Looking for protozero - found
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Osmium: Found unsuitable version "unknown", but required is
  at least "2.12.0" (found OSMIUM_INCLUDE_DIR-NOTFOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOsmium.cmake:294 (find_package_handle_standard_args)
  CMakeLists.txt:47 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by joto** [comment]
You have to install all dependencies first, see README.
