### ISSUE TITLE
`osmium tags-filter`: Broken pipe at 3.51G via stdin

### ISSUE THREAD

**Issue by cviebig** [osmcode/osmium-tool#54]
Hello everyone,

I am trying to stream the planet pbs file from a local http mirror using `curl` or `wget` to `osmium tags-filter` and experience a broken pipe at 3.51G being transferred.

Commands to reproduce:
```
wget -O - http://host/planet-latest.osm.pbf | osmium tags-filter - --omit-referenced --input-format pbf --output extract.osm.pbf [FILTER-EXPRESSION]
curl -o - http://host/planet-latest.osm.pbf | osmium tags-filter - --omit-referenced --input-format pbf --output extract.osm.pbf [FILTER-EXPRESSION]
```

wget output is:
```
HTTP request sent, awaiting response... 200 OK
Length: 37616433113 (35G) [application/octet-stream]
Saving to: ‘STDOUT’

-                    10%[=>                  ]   3.51G  13.3MB/s    in 4m 38s  


Cannot write to ‘-’ (Broken pipe).
failed to uncompress data: data error
```
I tested the same with a state-level extract and it completed fine. I also throttled the data transfer but this did not change the behavior. Are you able to reproduce this? I could not find the location of the code handling stdin so far but it seems it's located somewhere in `libosmium`, right? Can you please give me some thoughts on this issue?

Thank you very much in advance :-)

**Comment by joto** [comment]
`failed to uncompress data: data error` looks like it is coming from libosmium while it is trying to uncompress a PBF block. This most likely means that the data is corrupted.

Osmium can directly access a URL, so 

    osmium tags-filter http://host/planet-latest.osm.pbf --omit-referenced --input-format pbf --output extract.osm.pbf [FILTER-EXPRESSION]

should work, but will, of course, result in the same problem if the input data is corrupt. It uses `curl`, too, internally. But you can try this to see whether it makes a difference. But check your input file against a known good source.

**Comment by cviebig** [comment]
Oh, thanks for this quick answer, I'll check it. Have a nice day :-)
