### ISSUE TITLE
How to renumber multiple osm files？

### ISSUE THREAD

**Issue by sophia-xll** [osmcode/osmium-tool#58]
There is a problem that bothers me. if I run the command: "osmium renumber -i. -o 1_renumber.osm 1.osm",it works well. How to renumber another file from the last number that 1_renumber.osm used? I have trying to run "osmium renumber -i. -o 1_renumber.osm 1.osm  -o 2_renumber.osm 2.osm" and "osmium renumber -i. -o 1_renumber.osm 1.osm   2.osm", both of them occur "Error parsing command line: too many positional options have been specified on the command line".How to rename multiple osm files？Thanks for your reply.

**Comment by joto** [comment]
You just call `osmium renumber` several times, once for each input file. Just make sure to have the same `-i` option each time. There is an example in the manual page for this, but no good explanation, I'll add that to the manual page.

**Comment by sophia-xll** [comment]
Thanks for your quick and detailed reply. I have call _osmium renumber_ several times ,and It works well now.
Can this tool  renumber the first file starting from a given number, not 1?

**Comment by joto** [comment]
> Can this tool renumber the first file starting from a given number, not 1?

No.
