### ISSUE TITLE
from 1.3.0 to 1.6.1

### ISSUE THREAD

**Issue by istvanv-telenav** [osmcode/osmium-tool#60]
hi

I've managed to install version 1.3.0 and i'd like to upgrade it to 1.6.1
downloaded the latest version ran cmake and it installed successfully but when i run osmium it still sees the 1.3.0 version. could you  please guide me on how to make the changes? 
![image](https://user-images.githubusercontent.com/25033518/27520421-14c2d646-5a14-11e7-8bb6-bf513274ec58.png)

**Comment by joto** [comment]
Well, uninstall the old version.

**Comment by istvanv-telenav** [comment]
i'm pretty much new to this 
sudo apt-get remove osmium?

**Comment by istvanv-telenav** [comment]
i've removed the previous version installed the new one but when i call "osmium" it can't recognize the command.   Is there something i'm not doing right?

**Comment by joto** [comment]
Yes, there is. a) You are asking in the wrong place. This isn't a general newbie sysadmin help forum. b) You are not giving enought detail. Nobody can help you if you don't tell us what kind of system you have and exactly what commands you tried and which of them worked and which didn't.
