### ISSUE TITLE
OPL error for changeset with invalid coordinates (-214.7483648)

### ISSUE THREAD

**Issue by nrenner** [osmcode/osmium-tool#61]
[Not sure if this is an libosmium or osmium-tool issue. Don't actually need this, just to let you know.] 

When using [changesets-latest.osm.bz2](https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/planet/changesets-latest.osm.bz2) converted to OPL format with osmium-tool I got the following error:
`OPL error: expected space or tab character on line 153996 column 79`

That line (+1?) is without coordinates, but seems to work Ok:
```
$ head -n 153997 changesets-latest.opl | tail -n 1
c153997 k5 s2008-08-09T18:47:50Z e2008-08-09T19:47:52Z d0 i5748 upschonmann x y X Y T
```

But I noticed changeset [153980](http://www.openstreetmap.org/api/0.6/changeset/153980) with these coordinates in OPL:
`x-0../,),(-*,( y-29.4993277 X-0../,),(-*,( Y-29.4982071`
XML format:
`min_lat="-29.4993277" min_lon="-214.7483648" max_lat="-29.4982071" max_lon="-214.7483648"`

To reproduce:
```
$ wget -qO - http://www.openstreetmap.org/api/0.6/changeset/153980 | osmium cat -F .osm.xml -f .opl | osmium fileinfo -e -F .opl
...
OPL error: expected space or tab character on line 0 column 79
```

osmium-tool is build from current master on Ubuntu 16.04:
```
$ osmium --version
osmium version 1.6.1 (v1.6.1-11-gde9b3b5)
libosmium version 2.12.2
```

**Comment by mmd-osm** [comment]
Looks like osm.org is returning invalid data, the lon value has to be in the range -180<= lon <=180

**Comment by mmd-osm** [comment]
If I run osmium show on this broken changeset, I get at least an error message 'invalid location'. Still very strange that the osm server returns invalid data. Should probably be fixed upstream?

**Comment by joto** [comment]
Thanks for the report @nrenner. This should be fixed in libosmium master now.

@mmd-osm Yes, the server should not return such data, but unfortunately it creates a lot of bad data and we have to cope with that. Feel free try fixing this in the server.

**Comment by nrenner** [comment]
Confirming the fix, thanks.

I'm having fun with osmium-tool and the OPL format, thanks for providing these!
