### ISSUE TITLE
renumber error:Zero-sized mapping is not allowed

### ISSUE THREAD

**Issue by sophia-xll** [osmcode/osmium-tool#65]
Hello everyone,
    I want to renumber several osm files. When renumber the first osm after sorted ,everything works well ,the command is 'osmium renumber -i. -o a_renumber.osm a_sort.osm'. When renumber 2th osm after sorted in the same directory, like 'osmium renumber -i. -o b_renumber.osm b_sort.osm'.Error occurs 'Zero-sized mapping is not allowed'.
   The 2th osm was downloaded from Mappzen website with 490M size. The 1th osm was created myself with 40G size.
    What can I do to renumber osm files one by one ?Thanks for any help.

**Comment by sophia-xll** [comment]
Is this error because of  0KB relation.idx ?

**Comment by joto** [comment]
@sophia-xll Yes, this is the problem. Should be fixed now, but you need newest libosmium and osmium-tool master.

**Comment by sophia-xll** [comment]
Thanks for your reply. 
I have try to delete relation.idx. Then renumber another osm file at the same directory. This error doesn't occur any more.
