### ISSUE TITLE
renumber problem

### ISSUE THREAD

**Issue by sophia-xll** [osmcode/osmium-tool#66]
I import data into openstreetmap-website container ,and edit it ,then import another data into container. Steps below: 

1、Renumber several osm files at the same directory . the last id of node.idx is 1000 ,for example.
2、Merge osm files into one osm.pbf file . 
3、Import this pbf file into openstreetmap-website container using osmosis tool. 
4、Change sequence in postgresql database
5、Edit and save new elements in ID Editor,and node's id added from 1001 to 1020,for example.
6、At this time I renumber another osm file at the same directory,which  node.idx's last id is 1000 . and after renumber the node.idx's id added from 1001 to 2000. and I want to import this new osm file to openstreetmap-website container. Error occurs "Key (id)=(1000) already exist"

Do you have any suggestion to avoid key error?Thanks for any help.

**Comment by joto** [comment]
I don't think I can help here. There are too many programs involved here. Unless you can show some bad behaviour by the osmium program with a very detailed example, this is not something we can solve here.
