### ISSUE TITLE
Empty output file when running osmium extract with config option

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/osmium-tool#67]
I have a strange issue when making an extract with `osmium extract` command. 
When I use just a command line options everything goes ok, but when I use a config file, I get the same log, but the resulting osm extract is empty - just osm headers set inside the file, but no data.

I've tried:
- using geojson instead of poly file  
- changing `"output_format"` from `"pbf"` to `"osm"`
- setting strategies other than `smart`
- setting `"polygon":` instead of `"multipolygon":`

None of this helps. The extraction process takes the same amount of time like when running without config file, but the result is empty.

Running on
```
osmium version 1.7.0
libosmium version 2.13.0
```

Any clues?

**Comment by joto** [comment]
Could it have something to do with the directory setting in the config file and/or on the command line? Have you tried `--verbose`? Can you give me the exact command lines and config files you were using?

**Comment by nextstopsun** [comment]
At first I thought that may be connected with directory and it's permissions, but the extract file gets created and filled with osm headers, so I considered the issue to be elsewhere.

I use `--verbose` in both cases and the log output looks identical.

I use a command:
```
osmium extract -s smart -v --polygon /home/bezdna/osm-local/RU-MOW.poly RU-MOS.osm.pbf -o RU-MOW_noconf.pbf --overwrite
```

The command with config file:
```
osmium extract -s smart -v -c /home/bezdna/osm-local/test/extract_test.json /home/bezdna/osm-local/test/RU-MOS.osm.pbf --overwrite
```

My config is:
```
{
  "directory": "/home/bezdna/osm-local/test",
  "extracts": [
    {
      "output": "RU-MOW.osm",
      "output_format": "osm",
      "description": "Moscow",
      "polygon": {
        "file_name": "/home/bezdna/osm-local/RU-MOW.poly",
        "file_type": "poly"
      }
    }
  ]
}
```

**Comment by joto** [comment]
Uh. Thanks for finding this. A bug lead to all extracts specified via config file to be empty. Should be fixed in master now. I'll release a new version with the fix soon.

**Comment by nextstopsun** [comment]
Works now, thanks a lot @joto!
