### ISSUE TITLE
Add option to read just a header.option.timestamp value in osmium fileinfo

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/osmium-tool#68]
When issuing osmium fileinfo on a file that was generated with osmupdate or osmconvert (i.e. cumulated o5c changes file from osmupdate) it displays header options like
```
Header:
  Bounding boxes:
  With history: yes
  Options:
    o5m_timestamp=2017-08-25T08:00:02Z
    timestamp=2017-08-25T08:00:02Z
```
 
However, there is no `-g header.option.timestamp` key to diplay just the timestamp. 
Could this please be added?

I'd like to be able to write this header with `osmium apply-changes` and read back with `osmium fileinfo`, so I don't have to mess around with timestamps - put them in filenames or external files or wherever.

**Comment by joto** [comment]
Should work with current master.

**Comment by nextstopsun** [comment]
Thanks, @joto! I'll build from master and try it out.

**Comment by nextstopsun** [comment]
Ok, works now! Thanks, @joto!
