### ISSUE TITLE
Add osmium download-changes tool

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/osmium-tool#73]
The last bit missing in osmium tool is ability to download and cumulate planet changesets like `osmupdate`does.
I guess if this can be done in some form with `pyosmium`, it would be great to port it from there.
If this tool is in place, then my whole workflow involving `ogr2poly`, `osmupdate`, `osmfilter`, `osmconvert` and  would be replaced with just `osmium`, making it a universal tool, similar to `osmosis`, but times faster.

**Comment by joto** [comment]
I totally agree, I would like this, too. But it is unlikely to happen in the short run. The main reason is that there isn't a decent and widely available HTTP library for C++ that would make this a) easy to write for me and b) easy to compile for everybody. I recommend the programs supplied with Pyosmium which can do this and are really easy to use.

**Comment by nextstopsun** [comment]
Doesn't osmium depend on `curl`?

**Comment by joto** [comment]
Osmium can optionally use the `curl` binary for reading OSM files from the web. But this has always been somewhat of a hack. For one, detecting error conditions when using an external program is problematic. So I don't want to use that kind of solution for downloading change files, possibly loosing data in the process. And it doesn't work on Windows.

I have thought about using the `libcurl` library internally, but the interface for streaming use is horribly complicated and I couldn't figure out how to use it.

**Comment by joto** [comment]
This functionality is available in PyOsmiums [pyosmium-get-changes.py](https://docs.osmcode.org/pyosmium/latest/tools_get_changes.html) and [pyosmium-up-to-date.py](https://docs.osmcode.org/pyosmium/latest/tools_uptodate.html) which I recommend to use.
