### ISSUE TITLE
improve documentation when using export on OSM files created in JOSM

### ISSUE THREAD

**Issue by andrewharvey** [osmcode/osmium-tool#77]
I tried to use `osmium export` to convent an OSM file created in JOSM to GeoJSON. I found that it would silently omit LineStrings (only exporting Points). I couldn't find anything in the documentation to help.

When running with `-e` it reported that `Geometry error: need at least two points for linestring (way_id=-41997)`, which didn't make sense to me as the linestrings had more than two points.

I almost gave up but after remebering in the past I needed to use `osmium renumber` first, I gave that a go, which converted the negative IDs which JOSM creates into positive ones and suddenly osmium export correctly outputs LineStrings. Hooray :tada: 

The point of this issue is to help the next person who might run into this. I'm not sure how this should be addressed though?

1. Change osmimum export to work with the negative IDs JOSM creates in an OSM file.
2. Change the error message to hint that you need to use renumber first.
3. Include something in the documentation about using export with files created in JOSM with negative IDs needing to go through renumber first.

Any thoughts on the best way to improve this for users?

**Comment by springmeyer** [comment]
Thanks for creating this @andrewharvey. I'll leave the decision up to @joto - but I wonder if it would be viable to throw if negative IDs are encountered during `osmium export` and provide an error that instructs to use `osmium renumber`. I'm unaware if other applications give negative IDs?

**Comment by andrewharvey** [comment]
> but I wonder if it would be viable to throw if negative IDs are encountered during osmium export and provide an error that instructs to use osmium renumber. I'm unaware if other applications give negative IDs?

It's no big deal to renumber first, so if osmium reports an error message hinting this rather than silently failing that would be fine.

**Comment by joto** [comment]
I added support for negative IDs in the `export` command. @andrewharvey please verify that it works you you with the current master.

**Comment by andrewharvey** [comment]
Thanks @joto! I just tested again with stable where it wasn't exporting, then swapped over to master and it is exporting so all working :ok_hand: .
