### ISSUE TITLE
Ubuntu 16.04 installation problem

### ISSUE THREAD

**Issue by george-colin** [osmcode/osmium-tool#78]
Following the instructions at https://github.com/osmcode/osmium-tool, after:
cmake ..
I get:
...
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Osmium: Found unsuitable version "unknown", but required is
  at least "2.13.1" (found OSMIUM_INCLUDE_DIR-NOTFOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOsmium.cmake:294 (find_package_handle_standard_args)
  CMakeLists.txt:47 (find_package)

I have installed from repos as per the instructions.
This appears to be the same problem as #52

The fix is to ignore the instructions on:
"You also need the following libraries:

Libosmium (>= 2.13.1)
    http://osmcode.org/libosmium
    Debian/Ubuntu: libosmium2-dev"

and instead do:
git clone https://github.com/osmcode/libosmium.git

It seems that this is a problem several people have encountered - could an extra line in the instructions be added, in order to help users?  Thankyou.

**Comment by joto** [comment]
I have extended the build documentation in the README to make this clearer.
