### ISSUE TITLE
Allow exporting history files with osmium-export

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/osmium-tool#79]
Since there currently aren't any tools to import history files to db (i.e. to an `api db` schema) a good start would be to let `osh` files be exported to geojson format.

**Comment by joto** [comment]
It is unclear what exporting of a history file should do. You would need to export all versions of all objects I presume. This is a) difficult to do and would need huge amounts of memory to do on a planet file, b) generated quite a lot of data and c) I don't know of any software that could read such a GeoJSON file and do something sensible with it. You'd have to encode the object versions and/or time stamps of when object versions were created and deleted or superseeded in the GeoJSON. So, yes, something like this might be possible theoretically,  but I am not sure of the practicality of this. This also depends on your use case of course.

**Comment by nextstopsun** [comment]
Well it doesn't have to be a whole planet file. 
In my case it's an extract for a small region and a relatively small time interval. 
I just need to have each and every change, not just a diff from one to another timestamp. 

I guess technically it shouldn't be a hard implementation since history files have the same structure as osm ones and you don't have to generate a unique primary key column in geojson.
Regarding memory consumption etc. you'd probably have the same issue when trying to export a normal planet file to a geojson with this tool.
If I had OSM features history in a geojson, I could use GDAL (or split it and then use GDAL) to export to DB and then perform further data analysis.

@joto Do you know of any other appropriate tools for the task? The closest one I could find was [osm-history-renderer](https://github.com/MaZderMind/osm-history-renderer) but it was abandoned years ago and used an earlier version of libosmium, so can't be resurrected quick enough.

**Comment by joto** [comment]
The osm-history-renderer is the only tool I know of and it was abandoned because handling the history is much more difficult than it seems at first glance (and much more ressource intensive than handling a simple OSM file).
