### ISSUE TITLE
Need to specify libosmium include directory in order for make to work

### ISSUE THREAD

**Issue by cbdavis** [osmcode/osmium-tool#8]
I might be missing something in the documentation, but I'm unable to get `make` to work unless I explicitly specify the directory for libosmium/include in CMakeLists.txt

`include_directories(/home/UserName/Downloads/libosmium/include)`

Specifically, the issue seems to be that the code has include statements for hpp files which are only located in the libosmium git repository.

**Comment by joto** [comment]
Osmium-tool uses the usual CMake mechanisms for configuring the project. If you are not familiar with them, you have to get used to them first. Here are some tips:

CMake looks for Libosmium in a few places. If it finds it, it will just work. One of the places it looks for Libosmium is in `../libosmium`. So if you are using the git version, clone `libosmium` and `osmium-tool` in the same directory and it will find it.

If it doesn't find it, call `ccmake .` in the build directory after calling `cmake` and change the `OSMIUM_INCLUDE_DIR` variable. You can also do this on the `cmake` command line:

    cmake -DOSMIUM_INCLUDE_DIR=/home/UserName/Downloads/libosmium/include

**Comment by cbdavis** [comment]
Thanks for the help.  I tried a different computer (also running Ubuntu 14.10) and was able to get everything to work by using the following commands:

```
sudo apt-get install libboost-program-options-dev libboost-dev libprotobuf-dev protobuf-compiler libosmpbf-dev zlib1g-dev libexpat1-dev cmake pandoc
git clone https://github.com/osmcode/libosmium.git
git clone https://github.com/osmcode/osmium-tool.git
cd osmium-tool/
make
```
On the first computer I used, I still had the same problem even when doing a clean checkout.  Setting `OSMIUM_INCLUDE_DIR` as described in your post fixed everything.
