### ISSUE TITLE
When using tags-filter in history file, old objects are kept in snapshots

### ISSUE THREAD

**Issue by culebron** [osmcode/osmium-tool#86]
Example one: get historic snapshot, then filter by tags. Works correctly.

    osmium time-filter siberian-fed-district.osh.pbf 2018-03-01T00:00:00Z -o /tmp/snapshot.osm.pbf
    osmium tags-filter /tmp/snapshot.osm.pbf n/amenity n/shop -o /tmp/result.osm.pbf

It seemed a good idea to make it the other way around: filter by tags, get a very small file, then get its snapshot.

	osmium tags-filter siberian-fed-district.osh.pbf n/amenity n/shop -o /tmp/filtered.osh.pbf
	osmium time-filter /tmp/filtered.osh.pbf 2018-03-01T00:00:00Z -o /tmp/result.osm.pbf

Unfortunately, in the result there are points that were deleted. Is it possible to filter history files this way? It would give a great speed-up in making filtered snapshots.

**Comment by joto** [comment]
You should be able to do this if you add a `getid` step in between:

```
osmium tags-filter siberian-fed-district.osh.pbf n/amenity n/shop -o /tmp/ids.osh.pbf
osmium getid --id-osm-file /tmp/ids.osh.pbf --with-history siberian-fed-district.osh.pbf -o /tmp/filtered.osh.pbf
osmium time-filter /tmp/filtered.osh.pbf 2018-03-01T00:00:00Z -o /tmp/result.osm.pbf
```

The extra `osmium getid` makes sure *all* versions of all objects matched with the `tags-filter` are in the `filtered.osh.pbf` file. Then the `time-filter` can work as it should.

**Comment by culebron** [comment]
Worked as you wrote. Thanks  a lot!

**Comment by culebron** [comment]
Actually, each next snapshot now is almost free, because I have a filtered history file, and `time-filter` takes less than a second.

**Comment by joto** [comment]
I have added this info to the docs at http://osmcode.org/osmium-tool/manual.html#common-tasks.
