### ISSUE TITLE
extract the nodes who locate  outside the region.

### ISSUE THREAD

**Issue by LollipopKnight** [osmcode/osmium-tool#96]
Recently I'm working with the OSM history files. I was trying to extract the history data in a specific region. I use the command `extract --with-history` with a poly file, but I found it also crop some nodes who were not in the region. 
  I have also tried to extract OSM current file ( osh.pbf file, **not the history file anymore**) in the same region. To my surprise, it also crop some nodes not in the region !!! I have tried the same file using the osmosis tools and it works well, so I'm sure the OSM file and poly file that I used are OK. 
   I don't know  what's wrong with the osmium tools...

**Comment by joto** [comment]
There are several different strategies of extracing data from OSM files. You might have been using the wrong one for your use case, but your report is too vague to even begin to find out what might be wrong here. 

Describe exactly what you were trying to achieve, what you did, what you expected to happen and what did happen instead. Include relevant information about the platform, OS version etc. you are using. Include shell commands you typed in, log files, errors messages etc.

**Comment by LollipopKnight** [comment]
OK ,I'm trying to describe the issue with more details.

[Kowloon-AL5.txt](https://github.com/osmcode/osmium-tool/files/1824144/Kowloon-AL5.txt)
The file that I uploaded (Kowloon-AL5.txt) is actually a polygon file, which contains the coordinates of the boundary of Kowloon, HongKong. Due to the limitation of github, I have to change the suffix to `.txt`, but I use it with the suffix of `.poly`.

I also download the  OSM latest `china-latest.osm.pbf` of China from the [here](http://download.geofabrik.de/asia/china.html), this file contains the current status of OSM in China.

What I want to do was that use the osmium tool to  **extract the data which locate in Kowloon district described by the polygon file**.

According to the osmium tools manual ,I use the command below:
` osmium extract -p Kowloon-AL5.poly china-latest.osm.pbf -o kowloon.xml`
It showed no error and a file named "kowloon.xml" was created successfully.

But the problem is when I parse the XML file and plot the nodes, I found that there are some points who are not located in the region restricted by the polygon file.

Here is the shape of Kowloon ,Hongkong:
![kowloon](https://user-images.githubusercontent.com/17698816/37586904-b50f1762-2b98-11e8-8b11-c8ddca9416f8.png)
However, the distributions of the nodes likes this:
![osmium_kowloon](https://user-images.githubusercontent.com/17698816/37586933-d0a7cbb8-2b98-11e8-8eb1-bae2257b34d8.png)
As you can see, the distribution of the nodes was beyond the region limited by the shape of Kowloon.

Specifically, I run the command on MacOS Sierra, and the XML file and plots were handled by R. 
Here is the R code:
```r
library(XML)
library(ggplot2)
doc <- xmlParse("kowloon.xml")
root <- xmlRoot(doc)
# extract the nodes include coordinates ,it creates the xml nodesets object
Nodes <- xpathApply(doc,path = "/osm/node[@lat]")
#extract the attributes in every xml node
Nodes <- lapply(Nodes, xmlAttrs)
Nodes <- sapply(Nodes, function(x)x)
Nodes <- t(Nodes)
Nodes <- as.data.frame(Nodes,stringsAsFactors=FALSE)
lat <- as.numeric(Nodes$lat)
lon <- as.numeric(Nodes$lon)
spoints<- cbind(lat,lon)
spoints <- as.data.frame(spoints)
ggplot(spoints)+geom_point(aes(x=lon,y=lat))
```

Would you show the potential errors that I make ?

**Comment by LollipopKnight** [comment]
Sorry, I found where is the problem...
There is another parameter which was used to **choose the crop strategies**, I forgot to set the parameter.
If I use the command below:
`osmium extract --strategy=simple -p Kowloon-AL5.poly china-latest.osm.pbf -o kowloon.xml`
It will use the *simple* strategy to crop the region and will generate the desired result like this:
![osmium](https://user-images.githubusercontent.com/17698816/37589823-486d5b42-2ba1-11e8-94db-bbcb55a33b90.png)

By the way, thank you for providing such a useful tool !!!
